/**
 * Derived product taxonomy — normalizes the raw `size` field from
 * products.json into canonical filter values, and extracts color +
 * material from product names. All derived at read-time so
 * products.json stays untouched (it gets regenerated by the scraper).
 */

import type { Product } from "@/data/types";

/* ------------------------------------------------------------------ */
/* Size normalization                                                  */
/* ------------------------------------------------------------------ */

export type SizeBucket =
  /** Liquid volume in fluid ounces — drinkware. */
  | "oz"
  /** Two-axis dimension `W x H` — frames, journals, portfolios. */
  | "rect"
  /** Single linear measurement in inches. */
  | "inch"
  /** Diameter (cylindrical / circular items). */
  | "diam"
  /** Recognized format but doesn't fit any of the above. */
  | "other";

export interface NormalizedSize {
  raw: string;
  canonical: string;
  bucket: SizeBucket;
}

export function normalizeSize(raw: string | null | undefined): NormalizedSize | null {
  if (!raw) return null;
  const s = raw.trim().replace(/\.+$/, "");

  // oz volume
  const ozMatch = s.match(/^(\d+(?:\.\d+)?)\s*oz\.?$/i);
  if (ozMatch) {
    let n = ozMatch[1];
    if (n.endsWith(".0")) n = n.slice(0, -2);
    return { raw, canonical: `${n} oz`, bucket: "oz" };
  }

  if (/^[\d\s/.]+"\s*x\s*[\d\s/.]+"$/i.test(s)) {
    return { raw, canonical: s.replace(/\s*x\s*/i, " x "), bucket: "rect" };
  }

  const diamMatch = s.match(/^([\d\s/.]+)"\s*diameter$/i);
  if (diamMatch) {
    return { raw, canonical: `${diamMatch[1].trim()}" diameter`, bucket: "diam" };
  }

  if (/^[\d\s/.]+"$/i.test(s)) {
    return { raw, canonical: s, bucket: "inch" };
  }

  return { raw, canonical: s, bucket: "other" };
}

export function productSize(product: Product): NormalizedSize | null {
  return normalizeSize(product.size);
}

/* ------------------------------------------------------------------ */
/* Volume extraction (name-preferred)                                  */
/*                                                                     */
/* The supplier feed's `size` field for drinkware is inconsistent: a   */
/* "32 oz. Polar Camel Water Bottle" in olive green has size="32 oz."  */
/* but the same bottle in royal blue/red/black has size="11 1/2""      */
/* (just the height). The name, however, ALWAYS contains "32 oz." for  */
/* every variant. Pulling volume from the name first is the only way   */
/* to get a stable filter facet — fall back to the size field when     */
/* the name has no oz token (e.g. accessories without a volume).       */
/* ------------------------------------------------------------------ */

const NAME_VOLUME_RE = /\b(\d+(?:\.\d+)?)\s*oz\.?\b/i;

export function productVolume(product: Product): string | null {
  const m = product.name.match(NAME_VOLUME_RE);
  if (m) {
    let n = m[1];
    if (n.endsWith(".0")) n = n.slice(0, -2);
    return `${n} oz`;
  }
  const sized = productSize(product);
  return sized && sized.bucket === "oz" ? sized.canonical : null;
}

/* ------------------------------------------------------------------ */
/* Dimension bucketing — Small / Medium / Large                        */
/*                                                                     */
/* For non-drinkware subcategories that vary by physical dimension     */
/* (portfolios, frames, cutting boards, journals…) we bucket each      */
/* SKU into S / M / L using its primary size. The user-visible chips   */
/* become a manageable three-way navigation instead of 20+ exact       */
/* fractional measurements.                                            */
/* ------------------------------------------------------------------ */

export type SizeTier = "Small" | "Medium" | "Large";

function parseInchToken(s: string): number {
  // "5 1/4" / "1 1/2" / "10" — supplier uses these mixed forms.
  let total = 0;
  for (const piece of s.trim().split(/\s+/)) {
    if (piece.includes("/")) {
      const [num, den] = piece.split("/").map(Number);
      if (Number.isFinite(num) && Number.isFinite(den) && den !== 0) {
        total += num / den;
      }
    } else {
      const n = Number(piece);
      if (Number.isFinite(n)) total += n;
    }
  }
  return total;
}

export function productSizeTier(product: Product): SizeTier | null {
  const ns = productSize(product);
  if (!ns) return null;
  if (ns.bucket === "rect") {
    const m = ns.canonical.match(/^([\d\s/.]+)"\s*x\s*([\d\s/.]+)"$/);
    if (!m) return null;
    const a = parseInchToken(m[1]);
    const b = parseInchToken(m[2]);
    const area = a * b;
    if (area <= 0) return null;
    if (area < 45) return "Small";
    if (area < 110) return "Medium";
    return "Large";
  }
  if (ns.bucket === "inch") {
    const n = parseInchToken(ns.canonical.replace(/"/g, ""));
    if (n <= 0) return null;
    if (n < 5) return "Small";
    if (n < 9) return "Medium";
    return "Large";
  }
  if (ns.bucket === "diam") {
    const m = ns.canonical.match(/^([\d\s/.]+)"/);
    if (!m) return null;
    const n = parseInchToken(m[1]);
    if (n <= 0) return null;
    if (n < 4) return "Small";
    if (n < 8) return "Medium";
    return "Large";
  }
  return null;
}

const TIER_ORDER: Record<SizeTier, number> = {
  Small: 0,
  Medium: 1,
  Large: 2,
};

export function buildSizeTierFacets(
  products: Product[],
  { minCount = 2 }: { minCount?: number } = {},
): SimpleFacet[] {
  const counts = new Map<SizeTier, number>();
  for (const p of products) {
    const t = productSizeTier(p);
    if (!t) continue;
    counts.set(t, (counts.get(t) ?? 0) + 1);
  }
  return [...counts.entries()]
    .map(([canonical, count]) => ({ canonical, count }))
    .filter((f) => f.count >= minCount)
    .sort((a, b) => TIER_ORDER[a.canonical as SizeTier] - TIER_ORDER[b.canonical as SizeTier]);
}

export function filterBySizeTier(
  products: Product[],
  allowed: readonly string[],
): Product[] {
  if (allowed.length === 0) return products;
  const set = new Set(allowed);
  return products.filter((p) => {
    const t = productSizeTier(p);
    return t ? set.has(t) : false;
  });
}

/* ------------------------------------------------------------------ */
/* Color extraction                                                    */
/*                                                                     */
/* Most products encode color in the name: "Royal Blue 12 oz. Powder   */
/* Coated Water Bottle", "Aluminum Cake Pan with Navy Blue Powder      */
/* Coated Lid". We match against a canonical-with-aliases list,        */
/* longest alias first so "Royal Blue" wins over "Blue".               */
/* ------------------------------------------------------------------ */

interface KeywordGroup {
  canonical: string;
  aliases: string[];
  /** Hex used in the swatch chip. `null` = leave the swatch unfilled
   *  (for combos / wood tones we don't pretend to render exactly). */
  swatch?: string | string[] | null;
}

const COLOR_GROUPS: KeywordGroup[] = [
  { canonical: "Black", aliases: ["Black", "Jet Black", "Matte Black", "Onyx"], swatch: "#0f0f0f" },
  { canonical: "White", aliases: ["White", "Pearl White"], swatch: "#fafafa" },
  { canonical: "Cream", aliases: ["Cream", "Ivory", "Off-White", "Sand"], swatch: "#f5e9c8" },
  { canonical: "Red", aliases: ["Red", "Cherry Red", "Crimson"], swatch: "#c33a2c" },
  { canonical: "Burgundy", aliases: ["Burgundy", "Maroon", "Wine"], swatch: "#5e1a1a" },
  { canonical: "Pink", aliases: ["Hot Pink", "Light Pink", "Pink", "Rose"], swatch: "#e879a5" },
  { canonical: "Coral", aliases: ["Coral", "Salmon"], swatch: "#fb6f5f" },
  { canonical: "Orange", aliases: ["Orange"], swatch: "#f06a2a" },
  { canonical: "Yellow", aliases: ["Yellow"], swatch: "#f0c83a" },
  { canonical: "Gold", aliases: ["Gold", "Champagne"], swatch: "#c8a04a" },
  { canonical: "Copper", aliases: ["Copper", "Rose Gold"], swatch: "#b56a3a" },
  { canonical: "Bronze", aliases: ["Bronze"], swatch: "#8a5a30" },
  { canonical: "Brown", aliases: ["Dark Brown", "Light Brown", "Chocolate", "Espresso", "Brown"], swatch: "#6a3f23" },
  { canonical: "Beige", aliases: ["Beige", "Khaki", "Tan", "Taupe"], swatch: "#c8ad84" },
  { canonical: "Olive", aliases: ["Olive"], swatch: "#6a6a30" },
  { canonical: "Green", aliases: ["Forest Green", "Hunter Green", "Sage Green", "Mint Green", "Lime", "Green"], swatch: "#2f7a3f" },
  { canonical: "Teal", aliases: ["Teal", "Turquoise"], swatch: "#2da6a0" },
  { canonical: "Blue", aliases: ["Royal Blue", "Navy Blue", "Light Blue", "Powder Blue", "Sky Blue", "Aqua Blue", "Blue"], swatch: "#2a5acf" },
  { canonical: "Purple", aliases: ["Purple", "Violet", "Lavender", "Plum"], swatch: "#7d3ad0" },
  { canonical: "Charcoal", aliases: ["Charcoal"], swatch: "#3a3a3a" },
  { canonical: "Gray", aliases: ["Slate Gray", "Slate Grey", "Gray", "Grey"], swatch: "#7a7a7a" },
  { canonical: "Silver", aliases: ["Silver"], swatch: "#c2c2c4" },
  { canonical: "Camo", aliases: ["Camo", "Camouflage"], swatch: ["#3a4a2a", "#6a6a40", "#3a3a2a"] },
];

const MATERIAL_GROUPS: KeywordGroup[] = [
  { canonical: "Aluminum", aliases: ["Aluminum", "Aluminium"], swatch: "#b0b3b5" },
  { canonical: "Stainless Steel", aliases: ["Stainless Steel", "Stainless"], swatch: "#9aa0a4" },
  { canonical: "Bamboo", aliases: ["Bamboo"], swatch: "#cfa15a" },
  { canonical: "Walnut", aliases: ["Walnut"], swatch: "#5a3924" },
  { canonical: "Cherry", aliases: ["Cherry Wood", "Cherry"], swatch: "#83432a" },
  { canonical: "Maple", aliases: ["Maple"], swatch: "#c79460" },
  { canonical: "Oak", aliases: ["Oak"], swatch: "#a06a3a" },
  { canonical: "Wood", aliases: ["Wood", "Rosewood", "Mahogany"], swatch: "#7a4a2a" },
  { canonical: "Leatherette", aliases: ["Leatherette"], swatch: "#7a5a3a" },
  { canonical: "Leather", aliases: ["Leather"], swatch: "#6a3f23" },
  { canonical: "Cork", aliases: ["Cork"], swatch: "#c8a06a" },
  { canonical: "Glass", aliases: ["Glass", "Crystal", "Glassware"], swatch: "#cfe5ef" },
  { canonical: "Acrylic", aliases: ["Acrylic"], swatch: "#dadada" },
  { canonical: "Resin", aliases: ["Resin"], swatch: "#bca48a" },
  { canonical: "Marble", aliases: ["Marble"], swatch: "#dad7c4" },
  { canonical: "Slate", aliases: ["Slate"], swatch: "#535a63" },
  { canonical: "Polar Camel", aliases: ["Polar Camel"], swatch: null },
];

interface KeywordIndex {
  alias: string;
  aliasLower: string;
  re: RegExp;
  canonical: string;
}

function buildKeywordIndex(groups: KeywordGroup[]): KeywordIndex[] {
  const flat: KeywordIndex[] = [];
  for (const g of groups) {
    for (const alias of g.aliases) {
      flat.push({
        alias,
        aliasLower: alias.toLowerCase(),
        re: new RegExp(`\\b${alias.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "i"),
        canonical: g.canonical,
      });
    }
  }
  flat.sort((a, b) => b.alias.length - a.alias.length);
  return flat;
}

const COLOR_INDEX = buildKeywordIndex(COLOR_GROUPS);
const MATERIAL_INDEX = buildKeywordIndex(MATERIAL_GROUPS);

function extractFirst(name: string, idx: KeywordIndex[]): string | null {
  for (const entry of idx) {
    if (entry.re.test(name)) return entry.canonical;
  }
  return null;
}

export function productColor(p: Product): string | null {
  return extractFirst(p.name, COLOR_INDEX);
}

export function productMaterial(p: Product): string | null {
  return extractFirst(p.name, MATERIAL_INDEX);
}

export function colorSwatch(canonical: string): string | string[] | null {
  const g = COLOR_GROUPS.find((g) => g.canonical === canonical);
  return g?.swatch ?? null;
}

/* ------------------------------------------------------------------ */
/* Facet types + builders                                              */
/* ------------------------------------------------------------------ */

export interface SizeFacet {
  bucket: SizeBucket;
  canonical: string;
  count: number;
}

export interface SimpleFacet {
  canonical: string;
  count: number;
  swatch?: string | string[] | null;
}

export interface SubcategoryFacet {
  slug: string;
  name: string;
  count: number;
}

/**
 * Build volume facets ONLY. Linear / rectangular / diameter buckets
 * have been retired from the filter UI: they were either noise (one
 * chip per supplier-product, see "9 3/4" x 5/8"" on cake pans) or
 * misleading (bottle-height chips that look like "available sizes"
 * but are actually just the SKU's physical dimension). Volume is the
 * one continuous size facet that B2B buyers actually filter on, so
 * that's the only one we build.
 */
export function buildVolumeFacets(
  products: Product[],
  { minCount = 2 }: { minCount?: number } = {},
): SimpleFacet[] {
  const counts = new Map<string, number>();
  for (const p of products) {
    const v = productVolume(p);
    if (!v) continue;
    counts.set(v, (counts.get(v) ?? 0) + 1);
  }
  return [...counts.entries()]
    .map(([canonical, count]) => ({ canonical, count }))
    .filter((f) => f.count >= minCount)
    .sort((a, b) => {
      const an = parseFloat(a.canonical);
      const bn = parseFloat(b.canonical);
      if (!Number.isNaN(an) && !Number.isNaN(bn) && an !== bn) return an - bn;
      return a.canonical.localeCompare(b.canonical);
    });
}

export function buildColorFacets(
  products: Product[],
  { minCount = 2 }: { minCount?: number } = {},
): SimpleFacet[] {
  const counts = new Map<string, number>();
  for (const p of products) {
    const c = productColor(p);
    if (!c) continue;
    counts.set(c, (counts.get(c) ?? 0) + 1);
  }
  return [...counts.entries()]
    .map(([canonical, count]) => ({ canonical, count, swatch: colorSwatch(canonical) }))
    .filter((f) => f.count >= minCount)
    .sort((a, b) => b.count - a.count || a.canonical.localeCompare(b.canonical));
}

export function buildMaterialFacets(
  products: Product[],
  { minCount = 2 }: { minCount?: number } = {},
): SimpleFacet[] {
  const counts = new Map<string, number>();
  for (const p of products) {
    const m = productMaterial(p);
    if (!m) continue;
    counts.set(m, (counts.get(m) ?? 0) + 1);
  }
  return [...counts.entries()]
    .map(([canonical, count]) => ({ canonical, count }))
    .filter((f) => f.count >= minCount)
    .sort((a, b) => b.count - a.count || a.canonical.localeCompare(b.canonical));
}

export function buildSubcategoryFacets(products: Product[]): SubcategoryFacet[] {
  const counts = new Map<string, SubcategoryFacet>();
  for (const p of products) {
    const prev = counts.get(p.subcategorySlug);
    if (prev) prev.count += 1;
    else counts.set(p.subcategorySlug, {
      slug: p.subcategorySlug, name: p.subcategoryName, count: 1,
    });
  }
  return [...counts.values()].sort((a, b) => b.count - a.count);
}

/* ------------------------------------------------------------------ */
/* Per-page facet selection                                            */
/*                                                                     */
/* Volume + Color + Material are the three filter facets a B2B buyer   */
/* reaches for. Each is hidden when the page doesn't actually have ≥2  */
/* distinct values to choose from.                                     */
/* ------------------------------------------------------------------ */

export interface FacetPlan {
  showVolume: boolean;
  showColor: boolean;
  showMaterial: boolean;
}

export function planFacets(
  _products: Product[],
  volumeFacets: SimpleFacet[],
  colorFacets: SimpleFacet[],
  materialFacets: SimpleFacet[],
): FacetPlan {
  return {
    showVolume: volumeFacets.length >= 2,
    showColor: colorFacets.length >= 2,
    showMaterial: materialFacets.length >= 2,
  };
}

/* Kept for legacy callers that still ask for sizeFacets — returns the
 * volume-bucket subset only; the linear / rect / diam buckets are
 * permanently empty. New code should use buildVolumeFacets() directly. */
export function buildSizeFacets(
  products: Product[],
  opts: { minCount?: number } = {},
): SizeFacet[] {
  return buildVolumeFacets(products, opts).map((f) => ({
    bucket: "oz" as const,
    canonical: f.canonical,
    count: f.count,
  }));
}

/* ------------------------------------------------------------------ */
/* Filtering                                                           */
/* ------------------------------------------------------------------ */

export function filterByVolume(products: Product[], allowed: readonly string[]): Product[] {
  if (allowed.length === 0) return products;
  const set = new Set(allowed);
  return products.filter((p) => {
    const v = productVolume(p);
    return v ? set.has(v) : false;
  });
}

/** Legacy alias — old callers passed `?size=20+oz`, the canonical form
 *  is still "20 oz" so the values line up with filterByVolume. */
export const filterBySize = filterByVolume;

export function filterBySubcategory(products: Product[], allowed: readonly string[]): Product[] {
  if (allowed.length === 0) return products;
  const set = new Set(allowed);
  return products.filter((p) => set.has(p.subcategorySlug));
}

export function filterByColor(products: Product[], allowed: readonly string[]): Product[] {
  if (allowed.length === 0) return products;
  const set = new Set(allowed);
  return products.filter((p) => {
    const c = productColor(p);
    return c ? set.has(c) : false;
  });
}

export function filterByMaterial(products: Product[], allowed: readonly string[]): Product[] {
  if (allowed.length === 0) return products;
  const set = new Set(allowed);
  return products.filter((p) => {
    const m = productMaterial(p);
    return m ? set.has(m) : false;
  });
}
