/**
 * Derived product taxonomy — normalizes the raw `size` field from
 * products.json into canonical filter values and buckets.
 *
 * Why derived (not stored): the supplier feed mixes formats —
 * "20 oz." vs "20 oz" vs "20oz", "5 1/4"" vs "5 1/4" tall", etc.
 * Normalizing at read-time keeps products.json untouched (it gets
 * regenerated by the scraper) while letting the UI offer a clean,
 * groupable size filter.
 */

import type { Product } from "@/data/types";

export type SizeBucket =
  /** Liquid volume in fluid ounces — drinkware. */
  | "oz"
  /** Two-axis dimension `W x H` — frames, journals, portfolios. */
  | "rect"
  /** Single linear measurement in inches. */
  | "inch"
  /** Diameter (cylindrical / circular items). */
  | "diam"
  /** Recognized format but doesn't fit any of the above. */
  | "other";

export interface NormalizedSize {
  /** The original supplier string (untouched, for display fallback). */
  raw: string;
  /** Canonical filter value — used as the URL query param value. */
  canonical: string;
  bucket: SizeBucket;
}

/**
 * Normalize a raw size string. Returns `null` when the input is
 * `null`/empty so callers can simply skip products with no size.
 */
export function normalizeSize(raw: string | null | undefined): NormalizedSize | null {
  if (!raw) return null;
  const s = raw.trim().replace(/\.+$/, "");

  // oz volume: "20 oz", "20oz", "20 OZ.", "20.5 oz"
  const ozMatch = s.match(/^(\d+(?:\.\d+)?)\s*oz\.?$/i);
  if (ozMatch) {
    let n = ozMatch[1];
    if (n.endsWith(".0")) n = n.slice(0, -2);
    return { raw, canonical: `${n} oz`, bucket: "oz" };
  }

  // W x H dimensions: `5" x 7"`, `5 1/4" x 8 1/4"`
  if (/^[\d\s/.]+"\s*x\s*[\d\s/.]+"$/i.test(s)) {
    // collapse internal whitespace for canonical form
    return {
      raw,
      canonical: s.replace(/\s*x\s*/i, " x "),
      bucket: "rect",
    };
  }

  // Diameter: `4" diameter`, `3 1/2" diameter`
  const diamMatch = s.match(/^([\d\s/.]+)"\s*diameter$/i);
  if (diamMatch) {
    return {
      raw,
      canonical: `${diamMatch[1].trim()}" diameter`,
      bucket: "diam",
    };
  }

  // Single linear: `5 1/4"`, `7 3/4"`
  if (/^[\d\s/.]+"$/i.test(s)) {
    return { raw, canonical: s, bucket: "inch" };
  }

  return { raw, canonical: s, bucket: "other" };
}

export function productSize(product: Product): NormalizedSize | null {
  return normalizeSize(product.size);
}

/** A facet a filter UI can render. */
export interface SizeFacet {
  bucket: SizeBucket;
  canonical: string;
  count: number;
}

/**
 * Build the size facet list for a set of products. The list is ordered by
 * bucket priority (oz first, then rect, then inch, then diam, then other),
 * then by canonical-string sort within a bucket. Products without a
 * recognizable size are silently excluded.
 */
export function buildSizeFacets(products: Product[]): SizeFacet[] {
  const counts = new Map<string, SizeFacet>();
  for (const p of products) {
    const ns = productSize(p);
    if (!ns) continue;
    const key = `${ns.bucket}::${ns.canonical}`;
    const prev = counts.get(key);
    if (prev) prev.count += 1;
    else counts.set(key, { bucket: ns.bucket, canonical: ns.canonical, count: 1 });
  }
  const bucketRank: Record<SizeBucket, number> = {
    oz: 0,
    rect: 1,
    inch: 2,
    diam: 3,
    other: 4,
  };
  return [...counts.values()].sort((a, b) => {
    const r = bucketRank[a.bucket] - bucketRank[b.bucket];
    if (r !== 0) return r;
    // Numeric-ish compare within bucket so "12 oz" < "20 oz" < "100 oz",
    // and "4" x 6"" < "5" x 7"" < "8" x 10"".
    const an = parseFloat(a.canonical);
    const bn = parseFloat(b.canonical);
    if (!Number.isNaN(an) && !Number.isNaN(bn) && an !== bn) return an - bn;
    return a.canonical.localeCompare(b.canonical);
  });
}

/** Filter a product list by an array of allowed canonical size values. */
export function filterBySize(products: Product[], allowed: readonly string[]): Product[] {
  if (allowed.length === 0) return products;
  const set = new Set(allowed);
  return products.filter((p) => {
    const ns = productSize(p);
    return ns ? set.has(ns.canonical) : false;
  });
}

/**
 * Subcategory facet — used to surface popular subcategories on a category page.
 */
export interface SubcategoryFacet {
  slug: string;
  name: string;
  count: number;
}

export function buildSubcategoryFacets(products: Product[]): SubcategoryFacet[] {
  const counts = new Map<string, SubcategoryFacet>();
  for (const p of products) {
    const prev = counts.get(p.subcategorySlug);
    if (prev) prev.count += 1;
    else
      counts.set(p.subcategorySlug, {
        slug: p.subcategorySlug,
        name: p.subcategoryName,
        count: 1,
      });
  }
  return [...counts.values()].sort((a, b) => b.count - a.count);
}

/** Filter a product list by an array of allowed subcategory slugs. */
export function filterBySubcategory(
  products: Product[],
  allowed: readonly string[],
): Product[] {
  if (allowed.length === 0) return products;
  const set = new Set(allowed);
  return products.filter((p) => set.has(p.subcategorySlug));
}

/**
 * Parse the URL search-params shape used by category pages.
 * `?size=20+oz&size=40+oz&sub=tumblers&sub=water-bottles`
 */
export function parseCatalogFilters(params: URLSearchParams | undefined): {
  sizes: string[];
  subs: string[];
} {
  if (!params) return { sizes: [], subs: [] };
  return {
    sizes: params.getAll("size"),
    subs: params.getAll("sub"),
  };
}
