/**
 * FomaPrint catalog data layer.
 *
 * Product facts (names, SKUs, sizes, prices and product photography) are the
 * real catalog of our supplier/manufacturer, imported from products.json which
 * is generated by .scrape/scrape.py. FOMA FAMILY LLC is an authorized reseller
 * of this catalog. Presentation-only fields that the source feed does not
 * provide (lead time, badges, descriptions and personalization options) are
 * derived deterministically from each SKU so the catalog renders identically
 * on every server/client pass.
 *
 * This module imports the full dataset and must only be used from the server
 * (Server Components, route handlers, metadata). Client components should import
 * types from "@/data/types" and helpers from "@/lib/format".
 */

import rawData from "./products.json";
import productImagesRaw from "./product-images.json";
import productWeightsRaw from "./product-weights.json";
import { fomaProducts, FOMA_CATEGORY } from "./foma-products";
import type {
  Category,
  IconKey,
  PersonalizationOption,
  Product,
  SearchResult,
  Subcategory,
} from "./types";

export type {
  Category,
  IconKey,
  PersonalizationOption,
  PersonalizationType,
  Product,
  SearchResult,
  Subcategory,
} from "./types";

/* ------------------------------------------------------------------ */
/* Raw dataset shape                                                   */
/* ------------------------------------------------------------------ */

interface RawProduct {
  id: string;
  name: string;
  sku: string;
  size: string | null;
  price: number | null;
  image: string | null;
  imageFull: string | null;
  categoryId: string;
  categorySlug: string;
  categoryName: string;
  subId: string;
  subSlug: string;
  subName: string;
}

interface RawCategory {
  id: string;
  slug: string;
  name: string;
  subcategories: { subId: string; slug: string; name: string; count: number }[];
}

interface RawData {
  source: string;
  scrapedAt: string;
  categories: RawCategory[];
  products: RawProduct[];
}

const data = rawData as unknown as RawData;

/* ------------------------------------------------------------------ */
/* Brand normalization                                                 */
/*                                                                     */
/* The scraped feed mirrors the supplier's taxonomy, where insulated   */
/* "Polar Camel" drinkware is its own top-level category. FOMA presents */
/* it as one unified "Drinkware" category with the "Polar Camel"        */
/* trademark stripped from every name. We fold that category into       */
/* Drinkware here — the single point every consumer (pages, search,     */
/* sitemap) reads from — so it survives the daily re-scrape.            */
/* ------------------------------------------------------------------ */

const MERGE_SOURCE_SLUG = "polar-camel";
const MERGE_TARGET = { id: "3", slug: "drinkware", name: "Drinkware" } as const;

/* ------------------------------------------------------------------ */
/* SUB_OVERRIDES — re-home individual SKUs out of the supplier's       */
/* "ION-Plated Polar Camel Drinkware" lumped subcategory and into the  */
/* matching size + type subcategory the buyer expects (22 oz Skinny    */
/* tumblers → Skinny Tumblers, 32 oz water bottles → Water Bottles…).  */
/* After this override the "ION-Plated Drinkware" subcategory ends up  */
/* empty and gets dropped from the category nav automatically.         */
/* ------------------------------------------------------------------ */

interface SubAssignment {
  subId: string;
  subSlug: string;
  subName: string;
}
const SUB_OVERRIDES: Record<string, SubAssignment> = {
  // 22 oz Skinny Tumblers → Skinny Tumblers
  LTM7030: { subId: "17", subSlug: "polar-camel-skinny-tumblers", subName: "Polar Camel Skinny Tumblers" },
  LTM7031: { subId: "17", subSlug: "polar-camel-skinny-tumblers", subName: "Polar Camel Skinny Tumblers" },
  LTM7050: { subId: "17", subSlug: "polar-camel-skinny-tumblers", subName: "Polar Camel Skinny Tumblers" },
  LTM7051: { subId: "17", subSlug: "polar-camel-skinny-tumblers", subName: "Polar Camel Skinny Tumblers" },
  LTM7065: { subId: "17", subSlug: "polar-camel-skinny-tumblers", subName: "Polar Camel Skinny Tumblers" },
  LTM7066: { subId: "17", subSlug: "polar-camel-skinny-tumblers", subName: "Polar Camel Skinny Tumblers" },
  // 20 oz Ringneck/Tumblers → 20 oz. Tumblers
  LTM7280: { subId: "24", subSlug: "polar-camel-20-oz-tumblers", subName: "Polar Camel 20 oz. Tumblers" },
  LTM7281: { subId: "24", subSlug: "polar-camel-20-oz-tumblers", subName: "Polar Camel 20 oz. Tumblers" },
  LTM7282: { subId: "24", subSlug: "polar-camel-20-oz-tumblers", subName: "Polar Camel 20 oz. Tumblers" },
  LTM7283: { subId: "24", subSlug: "polar-camel-20-oz-tumblers", subName: "Polar Camel 20 oz. Tumblers" },
  LTM7284: { subId: "24", subSlug: "polar-camel-20-oz-tumblers", subName: "Polar Camel 20 oz. Tumblers" },
  LTM7285: { subId: "24", subSlug: "polar-camel-20-oz-tumblers", subName: "Polar Camel 20 oz. Tumblers" },
  LTM7290: { subId: "24", subSlug: "polar-camel-20-oz-tumblers", subName: "Polar Camel 20 oz. Tumblers" },
  LTM7291: { subId: "24", subSlug: "polar-camel-20-oz-tumblers", subName: "Polar Camel 20 oz. Tumblers" },
  LTM7295: { subId: "24", subSlug: "polar-camel-20-oz-tumblers", subName: "Polar Camel 20 oz. Tumblers" },
  LTM7296: { subId: "24", subSlug: "polar-camel-20-oz-tumblers", subName: "Polar Camel 20 oz. Tumblers" },
  // 40 oz Travel Mugs → Mugs/Travel Mugs
  LTM7430: { subId: "21", subSlug: "polar-camel-mugs-travel-mugs", subName: "Polar Camel Mugs/Travel Mugs" },
  LTM7431: { subId: "21", subSlug: "polar-camel-mugs-travel-mugs", subName: "Polar Camel Mugs/Travel Mugs" },
  LTM7432: { subId: "21", subSlug: "polar-camel-mugs-travel-mugs", subName: "Polar Camel Mugs/Travel Mugs" },
  LTM7433: { subId: "21", subSlug: "polar-camel-mugs-travel-mugs", subName: "Polar Camel Mugs/Travel Mugs" },
  LTM7434: { subId: "21", subSlug: "polar-camel-mugs-travel-mugs", subName: "Polar Camel Mugs/Travel Mugs" },
  LTM7435: { subId: "21", subSlug: "polar-camel-mugs-travel-mugs", subName: "Polar Camel Mugs/Travel Mugs" },
  LTM7470: { subId: "21", subSlug: "polar-camel-mugs-travel-mugs", subName: "Polar Camel Mugs/Travel Mugs" },
  LTM7471: { subId: "21", subSlug: "polar-camel-mugs-travel-mugs", subName: "Polar Camel Mugs/Travel Mugs" },
  LTM7485: { subId: "21", subSlug: "polar-camel-mugs-travel-mugs", subName: "Polar Camel Mugs/Travel Mugs" },
  LTM7486: { subId: "21", subSlug: "polar-camel-mugs-travel-mugs", subName: "Polar Camel Mugs/Travel Mugs" },
  // 12 oz Stemless Wine Tumblers → Stemless/Wine Chillers
  LTM870: { subId: "18", subSlug: "polar-camel-stemless-wine-chillers", subName: "Polar Camel Stemless/Wine Chillers" },
  LTM871: { subId: "18", subSlug: "polar-camel-stemless-wine-chillers", subName: "Polar Camel Stemless/Wine Chillers" },
  LTM880: { subId: "18", subSlug: "polar-camel-stemless-wine-chillers", subName: "Polar Camel Stemless/Wine Chillers" },
  LTM881: { subId: "18", subSlug: "polar-camel-stemless-wine-chillers", subName: "Polar Camel Stemless/Wine Chillers" },
  LTM890: { subId: "18", subSlug: "polar-camel-stemless-wine-chillers", subName: "Polar Camel Stemless/Wine Chillers" },
  LTM891: { subId: "18", subSlug: "polar-camel-stemless-wine-chillers", subName: "Polar Camel Stemless/Wine Chillers" },
  // 32 oz Water Bottles → Water Bottles
  LWB230: { subId: "14", subSlug: "polar-camel-water-bottles", subName: "Polar Camel Water Bottles" },
  LWB231: { subId: "14", subSlug: "polar-camel-water-bottles", subName: "Polar Camel Water Bottles" },
  LWB240: { subId: "14", subSlug: "polar-camel-water-bottles", subName: "Polar Camel Water Bottles" },
  LWB241: { subId: "14", subSlug: "polar-camel-water-bottles", subName: "Polar Camel Water Bottles" },
  LWB250: { subId: "14", subSlug: "polar-camel-water-bottles", subName: "Polar Camel Water Bottles" },
  LWB251: { subId: "14", subSlug: "polar-camel-water-bottles", subName: "Polar Camel Water Bottles" },
};

/* ------------------------------------------------------------------ */
/* Catalog curation (FomaPrint assortment, applied over the feed)      */
/*                                                                     */
/* The supplier feed is broader than what FOMA actually sells. These   */
/* lists trim it to the FomaPrint assortment and survive the daily     */
/* re-scrape because they are reapplied here, the single point every   */
/* consumer reads from:                                                */
/*   - REMOVED_SKUS: pulled from every page, search and sitemap.       */
/*   - ADDED_PRODUCTS: supplier items the feed doesn't carry, injected */
/*     idempotently so a later scrape that includes them won't dupe.   */
/*   - ADDED_SUBCATEGORIES: subcategory tiles those additions need.    */
/* ------------------------------------------------------------------ */

const REMOVED_SKUS = new Set<string>([
  "ADW10BK", "ADW10CL", "ADW8BK", "ADW8CL", "APF446B", "APF446GY",
  "APF457B", "APF457GY", "APF4810B", "APF4810GY", "BBQ01A", "BBQ02A",
  "BBQ03B", "BBQ11B", "BBQ12B", "BBQ13B", "BBQ14B", "BR2252",
  "BR2253", "CDL1011", "CDL1012", "CDL1013", "CDL1014", "CDL1015",
  "CDL1016", "CDL1017", "CDL1061", "CDL1062", "CDL1063", "CDL1064",
  "CDL1065", "CDL1066", "CDL1067", "DS10", "DS12", "DS20",
  "DS8", "FNL01", "FSK633", "FSK634", "FSK652SETA", "FSK655SETA",
  "FSK661SETA", "FSK671SET", "FSK672SET", "FSK675SET", "GFT008", "GFT010",
  "GFT024", "GFT045", "GFT048", "GFT049", "GFT1001", "GFT1002",
  "GFT1003", "GFT1004", "GFT1005", "GFT1006", "GFT1007", "GFT1008",
  "GFT1009", "GFT1010", "GFT1011", "GFT1012", "GFT1046", "GFT1047",
  "GFT1048", "GFT1049", "GFT105", "GFT1050", "GFT1051", "GFT1052",
  "GFT1053", "GFT1054", "GFT1055", "GFT1056", "GFT1057", "GFT1058",
  "GFT106", "GFT1136C", "GFT1137C", "GFT1138C", "GFT1139C", "GFT1141C",
  "GFT1143C", "GFT1144C", "GFT1146C", "GFT1147C", "GFT1165", "GFT1176",
  "GFT1178", "GFT1179", "GFT1183", "GFT1186", "GFT1188", "GFT1189",
  "GFT1190", "GFT1191", "GFT1244", "GFT1245", "GFT1246", "GFT1247",
  "GFT125", "GFT1257", "GFT126", "GFT127", "GFT1296", "GFT1297",
  "GFT1298", "GFT1300", "GFT1302", "GFT1304", "GFT1307", "GFT1311",
  "GFT1312", "GFT1313", "GFT1315", "GFT1316", "GFT1317", "GFT1318",
  "GFT159", "GFT169", "GFT170", "GFT171", "GFT172", "GFT173",
  "GFT174", "GFT185", "GFT192", "GFT198", "GFT2023", "GFT2024",
  "GFT2025", "GFT2026", "GFT2027", "GFT2028", "GFT2029", "GFT2030",
  "GFT2031", "GFT2032", "GFT2033", "GFT2034", "GFT2047", "GFT2048",
  "GFT2049", "GFT2071", "GFT2081", "GFT2091", "GFT2101", "GFT2102",
  "GFT2126", "GFT2127", "GFT219", "GFT220", "GFT221", "GFT2213",
  "GFT223", "GFT2316", "GFT2317", "GFT2318", "GFT2319", "GFT2320",
  "GFT2321", "GFT236", "GFT2364", "GFT2365", "GFT2425", "GFT245A",
  "GFT246A", "GFT261A", "GFT281", "GFT282", "GFT286", "GFT290",
  "GFT291", "GFT298", "GFT300", "GFT301", "GFT358", "GFT460",
  "GFT462BU", "GFT462GR", "GFT462NG", "GFT462PR", "GFT462RD", "GFT462YW",
  "GFT486", "GFT496", "GFT540", "GFT608", "GFT611", "GFT634",
  "GFT647", "GFT706", "GFT712", "GFT713", "GFT717", "GFT719",
  "GFT722", "GFT723", "GFT726", "GFT761", "GFT762", "GFT763",
  "GFT784", "GFT816", "GFT817", "GFT818", "GFT826", "GFT827",
  "GFT828", "GFT940", "GFT941", "HMD01", "LBH21", "LCM118",
  "LCM218", "LDC0102", "LDC0104", "LDC0105", "LDC0110", "LDC0111",
  "LDC0113", "LDC0202", "LDC0204", "LDC0205", "LDC0210", "LDC0211",
  "LDC0213", "LDC0302", "LDC0304", "LDC0305", "LDC0310", "LDC0311",
  "LDC0313", "LDC0402", "LDC0404", "LDC0405", "LDC0410", "LDC0411",
  "LDC0413", "LL11", "LLF1046", "LLF1057", "LLF10810", "LLF1246",
  "LLF1257", "LLF12810", "LLF146", "LLF1546", "LLF1557", "LLF157",
  "LLF15810", "LLF1646", "LLF1657", "LLF16810", "LLF1810", "LLF1846",
  "LLF18810", "LLF1946", "LLF1957", "LLF19810", "LLF246", "LLF257",
  "LLF2810", "LLF30146", "LLF30157", "LLF30346", "LLF30357", "LLF30446",
  "LLF30457", "LLF30546", "LLF30557", "LLF30946", "LLF30957", "LLF31246",
  "LLF31257", "LLF31346", "LLF31357", "LLF31446", "LLF31457", "LLF346A",
  "LLF357A", "LLF3810A", "LLF446", "LLF457", "LLF4810", "LLF546",
  "LLF557", "LLF5810", "LLF946", "LLF957", "LLF9810", "LLT01",
  "LLW3210A", "LLW328A", "LLW3310A", "LLW4210", "LLW428", "LLW4310",
  "LMG26", "LMG66", "LTM033", "LTM071", "LTM073", "LTM12L",
  "LTM20L", "LTM20MG", "LTM20SN", "LTM30L", "LTM30MG", "LTM30SN",
  "LTM5210", "LTM5212", "LTM7002", "LTM7003", "LTM7004", "LTM7005",
  "LTM7006", "LTM7007", "LTM7008", "LTM7009", "LTM7010", "LTM7011",
  "LTM7012", "LTM7013", "LTM7014", "LTM7015", "LTM7016", "LTM7017",
  "LTM7018", "LTM7219", "LTM7252", "LTM7253", "LTM7254", "LTM7255",
  "LTM7256", "LTM7257", "LTM7258", "LTM7259", "LTM7260", "LTM7261",
  "LTM7262", "LTM7263", "LTM7264", "LTM7265", "LTM7266", "LTM7267",
  "LTM7268", "LTM7269", "LTM7319", "LTM7352", "LTM7353", "LTM7354",
  "LTM7355", "LTM7356", "LTM7357", "LTM7358", "LTM7359", "LTM7360",
  "LTM7361", "LTM7362", "LTM7363", "LTM7364", "LTM7365", "LTM7366",
  "LTM7367", "LTM7368", "LTM7369", "LTM768", "LTM833", "LTM834",
  "LTM838", "MRT01", "PCG100", "PCG101", "PCG105", "PCG106",
  "PCG107", "PCG115", "PCG116", "PCG117", "PCG118", "PCG125",
  "PCG200", "PCG205", "PCG211", "PCG212", "PCG213", "PCG300",
  "PCG305", "PCG310", "PCG350", "PCG351", "PDL101", "PDL150",
  "PNA210", "PNA28", "PNA410", "PNA48", "PNB210", "PNB28",
  "PTF135", "PTF146", "PTF1810", "PTF1811", "PTF246", "PTF257",
  "PTF2810", "PTF457", "PTF4810", "PWR803C", "RA210", "RA28",
  "SLT010", "SLT011", "SLT020", "SLT021", "SLT030", "SLT031",
  "SLT040", "SLT041", "SLT042", "SLT050", "SLT051", "SLT085",
  "SLT086", "BPN101", "BPN102", "BPN103", "BPN104", "BPN105",
  "BR1001", "BR1002", "BR1003", "BR1004", "BR1251", "BR1252",
  "BR1253", "BR1501", "BR1502", "BR1751", "BR1752", "BR1753",
  "BR2001", "CH103", "CH104", "CH105", "CH109", "CH110",
  "CH111", "CH113", "FSK01", "FSK12", "GFT019", "GFT023",
  "GFT038", "GFT043", "GFT059", "GFT1265", "GFT1267", "GFT1268",
  "GFT1275", "GFT1276", "GFT1277", "GFT1299", "GFT1301", "GFT1303",
  "GFT1305", "GFT1306", "GFT131", "GFT132", "GFT133", "GFT134",
  "GFT160", "GFT161", "GFT162", "GFT163", "GFT164", "GFT165",
  "GFT166", "GFT167", "GFT179", "GFT180", "GFT2211", "GFT2212",
  "GFT2214", "GFT2215", "GFT2216", "GFT2217", "GFT2218", "GFT2219",
  "GFT222", "GFT2220", "GFT2221", "GFT2222", "GFT2223", "GFT2224",
  "GFT2225", "GFT2226", "GFT2227", "GFT224", "GFT2261", "GFT2262",
  "GFT2263", "GFT2264", "GFT2265", "GFT2266", "GFT2267", "GFT2268",
  "GFT2269", "GFT2270", "GFT2271", "GFT2272", "GFT2273", "GFT2274",
  "GFT2275", "GFT2276", "GFT2277", "GFT228A", "GFT232", "GFT2420",
  "GFT2421", "GFT2422", "GFT2423", "GFT2424", "GFT2435", "GFT2436",
  "GFT2437", "GFT2438", "GFT2439", "GFT243A", "GFT2440", "GFT264",
  "GFT273", "GFT278", "GFT368", "GFT369", "GFT370", "GFT371",
  "GFT386", "GFT400", "GFT440", "GFT445", "GFT446", "GFT447",
  "GFT448", "GFT449", "GFT470", "GFT471", "GFT472", "GFT481",
  "GFT482", "GFT483", "GFT484", "GFT491", "GFT492", "GFT493",
  "GFT494", "GFT495", "GFT530", "GFT531", "GFT534", "GFT538",
  "GFT539", "GFT541", "GFT542A", "GFT544", "GFT548", "GFT550",
  "GFT551", "GFT552A", "GFT554", "GFT558", "GFT604", "GFT610",
  "GFT661", "GFT662", "GFT663", "GFT664", "GFT665", "GFT667",
  "GFT668", "GFT669", "GFT670", "GFT733", "GFT734", "GFT735",
  "GFT776", "GFT802", "GFT811", "GFT813", "GFT832", "GFT865",
  "GFT866", "GFT890", "GFT891", "GFT892", "GFT895", "GFT896",
  "GFT897", "GFT898", "GFT902", "GFT921", "GFT922", "GFT990",
  "GFT991", "GFT992", "GFT993", "GSC101", "GSC102", "GSC103",
  "GSC104", "GSC201", "GSC202", "GSC203", "GSC301", "GSC302",
  "GSC303", "GSC304", "LSC101", "LSC102", "LSC103", "LSC104",
  "LSC105", "LSC106", "LSC107", "LSC108", "LTM072", "LTM076",
  "SLT060", "SLT061", "SLT062", "SLT071", "SLT075", "SLT076",
  "SLT077", "SLT078", "SLT079", "SLT080", "SLT081", "SLT088",
  "FSK101", "FSK102", "FSK103", "FSK104", "FSK111", "FSK303",
  "FSK309", "FSK312", "FSK628", "FSK651SETA", "GFT014", "GFT015",
  "BR2251", "BR2501",
]);

const ADDED_PRODUCTS: RawProduct[] = [
  // The five silicone-grip-coaster additions (GFT2071/2081/2091/2101/2102) were
  // marked "SIL (x)" in fomaprint liste.xlsx (2026-06-27 refresh) and dropped.
  // Their now-empty "Silicone Grip Coasters" subcategory was removed below.
  {
    id: "lbh21",
    name: "Stainless Steel Polar Camel Insulated Beverage Holder",
    sku: "LBH21",
    size: "5 1/4\"",
    price: 22.0,
    image: "https://res.cloudinary.com/business-products/image/upload/q_auto,c_pad,b_transparent,w_300,h_300/v1669755588/products/images/large/LBH21--df17df08.png",
    imageFull: "https://res.cloudinary.com/business-products/image/upload/q_auto/v1669755588/products/images/large/LBH21--df17df08.png",
    categoryId: "2",
    categorySlug: "polar-camel",
    categoryName: "Polar Camel",
    subId: "19",
    subSlug: "polar-camel-beverage-holders",
    subName: "Polar Camel Beverage Holders",
  },

  // New 2026/27 Polar Camel drinkware from the JDS DRINKCAT26 catalog, placed by
  // ACTUAL SIZE into the existing size subcategories (per user rule — size wins
  // over catalog page/name): the Bright Gold Ion & Ghost Black colors are 20 oz
  // tumblers; LTM7375-7379 are 32 oz travel mugs. Each name carries the oz so the
  // "Browse by size" filter buckets it. Images are JDS's official product shots
  // (hosted-by-files.com), re-hosted in public/jds-2026/. basePrice is the target
  // subcategory's median pending exact JDS pricing (hidden behind Add to quote).
  {
    id: "ltm7230",
    name: "Black/Bright Gold Ion 20 oz Tumbler",
    sku: "LTM7230",
    size: "20 oz.",
    price: 29,
    image: "/products/LTM7230/LTM7230.png",
    imageFull: "/products/LTM7230/LTM7230.png",
    categoryId: "2",
    categorySlug: "polar-camel",
    categoryName: "Polar Camel",
    subId: "24",
    subSlug: "polar-camel-20-oz-tumblers",
    subName: "Polar Camel 20 oz. Tumblers",
  },
  {
    id: "ltm7231",
    name: "Red/Bright Gold Ion 20 oz Tumbler",
    sku: "LTM7231",
    size: "20 oz.",
    price: 29,
    image: "/products/LTM7231/LTM7231.png",
    imageFull: "/products/LTM7231/LTM7231.png",
    categoryId: "2",
    categorySlug: "polar-camel",
    categoryName: "Polar Camel",
    subId: "24",
    subSlug: "polar-camel-20-oz-tumblers",
    subName: "Polar Camel 20 oz. Tumblers",
  },
  {
    id: "ltm7232",
    name: "Purple/Bright Gold Ion 20 oz Tumbler",
    sku: "LTM7232",
    size: "20 oz.",
    price: 29,
    image: "/products/LTM7232/LTM7232.png",
    imageFull: "/products/LTM7232/LTM7232.png",
    categoryId: "2",
    categorySlug: "polar-camel",
    categoryName: "Polar Camel",
    subId: "24",
    subSlug: "polar-camel-20-oz-tumblers",
    subName: "Polar Camel 20 oz. Tumblers",
  },
  {
    id: "ltm7233",
    name: "Navy/Bright Gold Ion 20 oz Tumbler",
    sku: "LTM7233",
    size: "20 oz.",
    price: 29,
    image: "/products/LTM7233/LTM7233.png",
    imageFull: "/products/LTM7233/LTM7233.png",
    categoryId: "2",
    categorySlug: "polar-camel",
    categoryName: "Polar Camel",
    subId: "24",
    subSlug: "polar-camel-20-oz-tumblers",
    subName: "Polar Camel 20 oz. Tumblers",
  },
  {
    id: "ltm7234",
    name: "Maroon/Bright Gold Ion 20 oz Tumbler",
    sku: "LTM7234",
    size: "20 oz.",
    price: 29,
    image: "/products/LTM7234/LTM7234.png",
    imageFull: "/products/LTM7234/LTM7234.png",
    categoryId: "2",
    categorySlug: "polar-camel",
    categoryName: "Polar Camel",
    subId: "24",
    subSlug: "polar-camel-20-oz-tumblers",
    subName: "Polar Camel 20 oz. Tumblers",
  },
  {
    id: "ltm7235",
    name: "Green/Bright Gold Ion 20 oz Tumbler",
    sku: "LTM7235",
    size: "20 oz.",
    price: 29,
    image: "/products/LTM7235/LTM7235.png",
    imageFull: "/products/LTM7235/LTM7235.png",
    categoryId: "2",
    categorySlug: "polar-camel",
    categoryName: "Polar Camel",
    subId: "24",
    subSlug: "polar-camel-20-oz-tumblers",
    subName: "Polar Camel 20 oz. Tumblers",
  },
  {
    id: "ltm7278",
    name: "Orange/Ghost Black 20 oz Tumbler",
    sku: "LTM7278",
    size: "20 oz.",
    price: 29,
    image: "/products/LTM7278/LTM7278.png",
    imageFull: "/products/LTM7278/LTM7278.png",
    categoryId: "2",
    categorySlug: "polar-camel",
    categoryName: "Polar Camel",
    subId: "24",
    subSlug: "polar-camel-20-oz-tumblers",
    subName: "Polar Camel 20 oz. Tumblers",
  },
  {
    id: "ltm7279",
    name: "Yellow/Ghost Black 20 oz Tumbler",
    sku: "LTM7279",
    size: "20 oz.",
    price: 29,
    image: "/products/LTM7279/LTM7279.png",
    imageFull: "/products/LTM7279/LTM7279.png",
    categoryId: "2",
    categorySlug: "polar-camel",
    categoryName: "Polar Camel",
    subId: "24",
    subSlug: "polar-camel-20-oz-tumblers",
    subName: "Polar Camel 20 oz. Tumblers",
  },
  {
    id: "ltm7375",
    name: "Black 32 oz Travel Mug",
    sku: "LTM7375",
    size: "32 oz.",
    price: 41.25,
    image: "/products/LTM7375/LTM7375.png",
    imageFull: "/products/LTM7375/LTM7375.png",
    categoryId: "2",
    categorySlug: "polar-camel",
    categoryName: "Polar Camel",
    subId: "21",
    subSlug: "polar-camel-mugs-travel-mugs",
    subName: "Polar Camel Mugs/Travel Mugs",
  },
  {
    id: "ltm7376",
    name: "White 32 oz Travel Mug",
    sku: "LTM7376",
    size: "32 oz.",
    price: 41.25,
    image: "/products/LTM7376/LTM7376.png",
    imageFull: "/products/LTM7376/LTM7376.png",
    categoryId: "2",
    categorySlug: "polar-camel",
    categoryName: "Polar Camel",
    subId: "21",
    subSlug: "polar-camel-mugs-travel-mugs",
    subName: "Polar Camel Mugs/Travel Mugs",
  },
  {
    id: "ltm7377",
    name: "Navy Blue 32 oz Travel Mug",
    sku: "LTM7377",
    size: "32 oz.",
    price: 41.25,
    image: "/products/LTM7377/LTM7377.png",
    imageFull: "/products/LTM7377/LTM7377.png",
    categoryId: "2",
    categorySlug: "polar-camel",
    categoryName: "Polar Camel",
    subId: "21",
    subSlug: "polar-camel-mugs-travel-mugs",
    subName: "Polar Camel Mugs/Travel Mugs",
  },
  {
    id: "ltm7378",
    name: "Red 32 oz Travel Mug",
    sku: "LTM7378",
    size: "32 oz.",
    price: 41.25,
    image: "/products/LTM7378/LTM7378.png",
    imageFull: "/products/LTM7378/LTM7378.png",
    categoryId: "2",
    categorySlug: "polar-camel",
    categoryName: "Polar Camel",
    subId: "21",
    subSlug: "polar-camel-mugs-travel-mugs",
    subName: "Polar Camel Mugs/Travel Mugs",
  },
  {
    id: "ltm7379",
    name: "Royal Blue 32 oz Travel Mug",
    sku: "LTM7379",
    size: "32 oz.",
    price: 41.25,
    image: "/products/LTM7379/LTM7379.png",
    imageFull: "/products/LTM7379/LTM7379.png",
    categoryId: "2",
    categorySlug: "polar-camel",
    categoryName: "Polar Camel",
    subId: "21",
    subSlug: "polar-camel-mugs-travel-mugs",
    subName: "Polar Camel Mugs/Travel Mugs",
  },
];

/* New subcategories the additions introduce, keyed by the (post-merge)
   category slug they belong under. Count is recomputed from products. */
const ADDED_SUBCATEGORIES: Record<string, RawCategory["subcategories"]> = {};

function stripBrand(text: string): string {
  return text
    .replace(/\bpolar\s+camel\b/gi, " ")
    .replace(/\s+([.,])/g, "$1")
    .replace(/\s{2,}/g, " ")
    .trim();
}

function stripBrandSlug(slug: string): string {
  const cleaned = slug
    .replace(/polar-camel-?/g, "")
    .replace(/(^-+)|(-+$)/g, "")
    .replace(/-{2,}/g, "-");
  return cleaned || slug;
}

function normalizeCatalog(): { products: RawProduct[]; categories: RawCategory[] } {
  const subSlugBySubId = new Map<string, string>();
  const categories: RawCategory[] = [];
  let target: RawCategory | undefined;

  const addSub = (cat: RawCategory, sc: RawCategory["subcategories"][number]) => {
    let slug = stripBrandSlug(sc.slug);
    const taken = new Set(cat.subcategories.map((s) => s.slug));
    if (taken.has(slug)) {
      let i = 2;
      while (taken.has(`${slug}-${i}`)) i++;
      slug = `${slug}-${i}`;
    }
    subSlugBySubId.set(sc.subId, slug);
    cat.subcategories.push({ ...sc, slug, name: stripBrand(sc.name) });
  };

  for (const c of data.categories) {
    if (c.slug === MERGE_SOURCE_SLUG || c.slug === MERGE_TARGET.slug) {
      if (!target) {
        target = { ...MERGE_TARGET, subcategories: [] };
        categories.push(target);
      }
      for (const sc of c.subcategories) addSub(target, sc);
      continue;
    }
    const cat: RawCategory = { ...c, subcategories: [] };
    categories.push(cat);
    for (const sc of c.subcategories) addSub(cat, sc);
  }

  // Append any FomaPrint-introduced subcategories to their category.
  for (const cat of categories) {
    for (const sc of ADDED_SUBCATEGORIES[cat.slug] ?? []) addSub(cat, sc);
  }

  // Trim the feed to the FomaPrint assortment, then inject curated additions
  // the scrape doesn't carry (skipping any a later scrape may already include).
  const kept = data.products.filter(
    (p) => !REMOVED_SKUS.has(p.sku.toUpperCase()),
  );
  const present = new Set(kept.map((p) => p.sku.toUpperCase()));
  const sourceProducts = [
    ...kept,
    ...ADDED_PRODUCTS.filter((p) => !present.has(p.sku.toUpperCase())),
  ];

  const products = sourceProducts.map((p) => {
    const merged = p.categorySlug === MERGE_SOURCE_SLUG;
    const override = SUB_OVERRIDES[p.sku.toUpperCase()];
    const effectiveSubId = override?.subId ?? p.subId;
    const fallbackSlug = subSlugBySubId.get(effectiveSubId) ?? p.subSlug;
    return {
      ...p,
      name: stripBrand(p.name),
      categoryId: merged ? MERGE_TARGET.id : p.categoryId,
      categorySlug: merged ? MERGE_TARGET.slug : p.categorySlug,
      categoryName: merged ? MERGE_TARGET.name : p.categoryName,
      subId: effectiveSubId,
      subSlug: override
        ? subSlugBySubId.get(override.subId) ?? override.subSlug
        : fallbackSlug,
      subName: stripBrand(override?.subName ?? p.subName),
    };
  });

  return { products, categories };
}

const { products: normProducts, categories: normCategories } = normalizeCatalog();

/* ------------------------------------------------------------------ */
/* Presentation metadata (authored)                                    */
/* ------------------------------------------------------------------ */

const CATEGORY_ICONS: Record<string, IconKey> = {
  "best-seller": "award",
  "gifts-and-promotions": "gift",
  drinkware: "coffee",
  "frames-and-decor": "frame",
  "office-tech": "notebook",
};

const CATEGORY_BLURBS: Record<string, string> = {
  "best-seller":
    "Our own laser-engraved best sellers — personalized tumblers and lighters, made to order by FOMA FAMILY LLC.",
  "gifts-and-promotions":
    "Laser-engraved keepsakes, awards, barware and promotional gifts for every milestone.",
  drinkware:
    "Insulated tumblers, water bottles, mugs, coasters and glassware ready for crisp, permanent engraving.",
  "frames-and-decor":
    "Photo frames, slate signage and ornaments that turn moments into heirlooms.",
  "office-tech":
    "Journals, portfolios and desk accessories engraved for teams and gifting.",
};

const DEFAULT_ICON: IconKey = "gift";

/* ------------------------------------------------------------------ */
/* Deterministic derivation helpers                                    */
/* ------------------------------------------------------------------ */

function xmur3(str: string): () => number {
  let h = 1779033703 ^ str.length;
  for (let i = 0; i < str.length; i++) {
    h = Math.imul(h ^ str.charCodeAt(i), 3432918353);
    h = (h << 13) | (h >>> 19);
  }
  return () => {
    h = Math.imul(h ^ (h >>> 16), 2246822507);
    h = Math.imul(h ^ (h >>> 13), 3266489909);
    return (h ^= h >>> 16) >>> 0;
  };
}

function mulberry32(a: number): () => number {
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function rngFor(seed: string): () => number {
  return mulberry32(xmur3(seed)());
}

function intBetween(rng: () => number, min: number, max: number): number {
  return Math.floor(rng() * (max - min + 1)) + min;
}

const FONT_OPTIONS = [
  "Classic Serif",
  "Modern Sans",
  "Elegant Script",
  "Block Capitals",
];

function buildPersonalization(): PersonalizationOption[] {
  return [
    {
      id: "engraving",
      label: "Engraving text",
      type: "text",
      required: true,
      placeholder: "Name, date, or short message",
      helpText: "Up to 40 characters. Add line breaks or extra detail in notes.",
      maxLength: 40,
    },
    {
      id: "font",
      label: "Font style",
      type: "select",
      required: false,
      options: FONT_OPTIONS,
    },
  ];
}

function buildDescriptions(p: RawProduct): {
  description: string;
  longDescription: string;
} {
  const sizePart = p.size ? ` (${p.size})` : "";
  const description = `${p.name}${sizePart}, ready to personalize with laser engraving — add a name, date, monogram or logo for a crisp, permanent finish.`;
  const longDescription = `The ${p.name} is part of our ${p.subName} collection and is precision laser-engraved to order in the USA. Customize it with a name, date, monogram, or your company logo for a sharp, permanent mark that won't fade or peel — ideal for gifts, weddings, corporate orders and milestone awards. ${
    p.size ? `Size: ${p.size}. ` : ""
  }Personalization is included; volume and corporate pricing available on request.`;
  return { description, longDescription };
}

/* ------------------------------------------------------------------ */
/* Build the catalog once at module load                               */
/* ------------------------------------------------------------------ */

const jdsProducts: Product[] = normProducts.map((p) => {
  const rng = rngFor(p.sku);
  const leadTimeDays = intBetween(rng, 5, 14);
  const badges: string[] = [];
  const roll = rng();
  if (roll < 0.14) badges.push("Bestseller");
  else if (roll < 0.26) badges.push("New");
  const { description, longDescription } = buildDescriptions(p);
  const image = p.image ?? p.imageFull ?? "";
  return {
    id: p.id,
    name: p.name,
    sku: p.sku,
    size: p.size,
    basePrice: p.price ?? 0,
    image,
    imageFull: p.imageFull ?? image,
    categoryId: p.categoryId,
    categorySlug: p.categorySlug,
    categoryName: p.categoryName,
    subcategorySlug: p.subSlug,
    subcategoryName: p.subName,
    description,
    longDescription,
    badges,
    leadTimeDays,
    personalization: buildPersonalization(),
  };
});

// Curated multi-view image galleries, keyed by SKU (case-insensitive).
// Source: .scrape/incoming/Product_images bound to catalog SKUs by
// .scrape/overnight/build_image_report.py — the binaries themselves are
// served from /public/products/{SKU}/ but are NOT committed (volume >> 500MB);
// only the URL bindings live in src/data/product-images.json.
const productImagesByUpper = new Map<string, string[]>(
  Object.entries(productImagesRaw as Record<string, string[]>).map(
    ([k, v]) => [k.toUpperCase(), v],
  ),
);

// Per-SKU shipping weight (pounds). Source: FOMA's master spreadsheet,
// stored in src/data/product-weights.json. Surfaced as `Product.weightLb`,
// rendered on the detail page's spec list, AND appended as a sentence to
// the product's longDescription so the lb figure shows up in body copy
// + SEO metadata.
const productWeightsByUpper = new Map<string, number>(
  Object.entries(productWeightsRaw as Record<string, number>).map(
    ([k, v]) => [k.toUpperCase(), v],
  ),
);

function formatLbForDescription(lb: number): string {
  const lbPlaces = lb < 1 ? 2 : lb < 10 ? 1 : 0;
  const oz = lb * 16;
  const ozPlaces = oz < 10 ? 1 : 0;
  return `${lb.toFixed(lbPlaces)} lb (${oz.toFixed(ozPlaces)} oz)`;
}

function enrich(p: Product): Product {
  const upper = p.sku.toUpperCase();
  const images = productImagesByUpper.get(upper);
  const weightLb = productWeightsByUpper.get(upper);
  let next = p;
  if (images && images.length > 0) next = { ...next, images };
  if (weightLb !== undefined && weightLb > 0) {
    const weightSentence = ` Approximate shipping weight: ${formatLbForDescription(weightLb)}.`;
    next = {
      ...next,
      weightLb,
      longDescription: next.longDescription.endsWith(weightSentence)
        ? next.longDescription
        : next.longDescription + weightSentence,
    };
  }
  return next;
}

// FOMA's own inventory (foma-products.ts) is merged in alongside the reseller
// catalog without altering it. The curated gallery + weight enrichments are
// applied uniformly so any future FOMA SKU can pick up its bindings the same way.
const allProducts: Product[] = [...jdsProducts, ...fomaProducts].map(enrich);

const productById = new Map(allProducts.map((p) => [p.id, p]));

const productsByCategory = new Map<string, Product[]>();
const productsBySub = new Map<string, Product[]>();
for (const p of allProducts) {
  const cKey = p.categorySlug;
  const sKey = `${p.categorySlug}/${p.subcategorySlug}`;
  (productsByCategory.get(cKey) ?? productsByCategory.set(cKey, []).get(cKey)!).push(p);
  (productsBySub.get(sKey) ?? productsBySub.set(sKey, []).get(sKey)!).push(p);
}

const categories: Category[] = [...normCategories, FOMA_CATEGORY].map((c) => {
  const subcategories: Subcategory[] = c.subcategories
    .map((sc) => {
      const items = productsBySub.get(`${c.slug}/${sc.slug}`) ?? [];
      return {
        slug: sc.slug,
        name: sc.name,
        blurb: `Personalized ${sc.name.toLowerCase()}, laser-engraved to order.`,
        productCount: items.length,
      };
    })
    // Drop tiles a curation left empty so the grid never shows "0 products".
    .filter((sc) => sc.productCount > 0);
  return {
    slug: c.slug,
    name: c.name,
    blurb: CATEGORY_BLURBS[c.slug] ?? `Personalized ${c.name.toLowerCase()}.`,
    icon: CATEGORY_ICONS[c.slug] ?? DEFAULT_ICON,
    subcategories,
    productCount: productsByCategory.get(c.slug)?.length ?? 0,
  };
});

const categoryBySlug = new Map(categories.map((c) => [c.slug, c]));

/* ------------------------------------------------------------------ */
/* Public API                                                          */
/* ------------------------------------------------------------------ */

export function getCategories(): Category[] {
  return categories;
}

export function getCategory(slug: string): Category | undefined {
  return categoryBySlug.get(slug);
}

export function getSubcategory(
  categorySlug: string,
  subSlug: string,
): { category: Category; subcategory: Subcategory } | undefined {
  const category = categoryBySlug.get(categorySlug);
  const subcategory = category?.subcategories.find((sc) => sc.slug === subSlug);
  if (!category || !subcategory) return undefined;
  return { category, subcategory };
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return productsByCategory.get(categorySlug) ?? [];
}

export function getProductsBySubcategory(
  categorySlug: string,
  subSlug: string,
): Product[] {
  return productsBySub.get(`${categorySlug}/${subSlug}`) ?? [];
}

export function getProduct(id: string): Product | undefined {
  return productById.get(id);
}

export function getAllProducts(): Product[] {
  return allProducts;
}

export function getProductCount(): number {
  return allProducts.length;
}

export function getFeaturedProducts(limit = 8): Product[] {
  const bestsellers = allProducts.filter((p) => p.badges.includes("Bestseller"));
  const pool = bestsellers.length >= limit ? bestsellers : allProducts;
  // Spread across categories for visual variety, then sort by rating.
  const byCat = new Map<string, Product[]>();
  for (const p of pool) {
    (byCat.get(p.categorySlug) ?? byCat.set(p.categorySlug, []).get(p.categorySlug)!).push(p);
  }
  // Deterministic per-SKU order so the featured rail is stable across renders
  // and varied across categories (round-robin below) without relying on ratings.
  const rank = (sku: string) => xmur3(sku)();
  for (const list of byCat.values()) list.sort((a, b) => rank(a.sku) - rank(b.sku));
  const out: Product[] = [];
  let added = true;
  while (out.length < limit && added) {
    added = false;
    for (const list of byCat.values()) {
      const next = list.shift();
      if (next) {
        out.push(next);
        added = true;
        if (out.length >= limit) break;
      }
    }
  }
  return out;
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  const sameSub = getProductsBySubcategory(
    product.categorySlug,
    product.subcategorySlug,
  ).filter((p) => p.id !== product.id);
  const sameCat = getProductsByCategory(product.categorySlug).filter(
    (p) =>
      p.id !== product.id && p.subcategorySlug !== product.subcategorySlug,
  );
  return [...sameSub, ...sameCat].slice(0, limit);
}

export function searchProducts(query: string, limit = 48): Product[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const terms = q.split(/\s+/);
  return allProducts
    .filter((p) => {
      const haystack =
        `${p.name} ${p.sku} ${p.categoryName} ${p.subcategoryName}`.toLowerCase();
      return terms.every((t) => haystack.includes(t));
    })
    .slice(0, limit);
}

/** Slim index for client-side live search suggestions. */
export function getSearchIndex(): SearchResult[] {
  return allProducts.map((p) => ({
    id: p.id,
    name: p.name,
    categoryName: p.categoryName,
    subcategoryName: p.subcategoryName,
    categorySlug: p.categorySlug,
    subcategorySlug: p.subcategorySlug,
    basePrice: p.basePrice,
    image: p.image,
  }));
}

export { formatPrice } from "@/lib/format";
