/**
 * FomaPrint catalog data layer.
 *
 * Product facts (names, SKUs, sizes, prices and product photography) are the
 * real catalog of our supplier/manufacturer, imported from products.json which
 * is generated by .scrape/scrape.py. FOMA FAMILY LLC is an authorized reseller
 * of this catalog. Presentation-only fields that the source feed does not
 * provide (lead time, badges, descriptions and personalization options) are
 * derived deterministically from each SKU so the catalog renders identically
 * on every server/client pass.
 *
 * This module imports the full dataset and must only be used from the server
 * (Server Components, route handlers, metadata). Client components should import
 * types from "@/data/types" and helpers from "@/lib/format".
 */

import rawData from "./products.json";
import { fomaProducts, FOMA_CATEGORY } from "./foma-products";
import type {
  Category,
  IconKey,
  PersonalizationOption,
  Product,
  SearchResult,
  Subcategory,
} from "./types";

export type {
  Category,
  IconKey,
  PersonalizationOption,
  PersonalizationType,
  Product,
  SearchResult,
  Subcategory,
} from "./types";

/* ------------------------------------------------------------------ */
/* Raw dataset shape                                                   */
/* ------------------------------------------------------------------ */

interface RawProduct {
  id: string;
  name: string;
  sku: string;
  size: string | null;
  price: number | null;
  image: string | null;
  imageFull: string | null;
  categoryId: string;
  categorySlug: string;
  categoryName: string;
  subId: string;
  subSlug: string;
  subName: string;
}

interface RawCategory {
  id: string;
  slug: string;
  name: string;
  subcategories: { subId: string; slug: string; name: string; count: number }[];
}

interface RawData {
  source: string;
  scrapedAt: string;
  categories: RawCategory[];
  products: RawProduct[];
}

const data = rawData as unknown as RawData;

/* ------------------------------------------------------------------ */
/* Presentation metadata (authored)                                    */
/* ------------------------------------------------------------------ */

const CATEGORY_ICONS: Record<string, IconKey> = {
  "best-seller": "award",
  "gifts-and-promotions": "gift",
  "polar-camel": "cup-soda",
  drinkware: "coffee",
  "frames-and-decor": "frame",
  "office-tech": "notebook",
};

const CATEGORY_BLURBS: Record<string, string> = {
  "best-seller":
    "Our own laser-engraved best sellers — personalized tumblers and lighters, made to order by FOMA FAMILY LLC.",
  "gifts-and-promotions":
    "Laser-engraved keepsakes, awards, barware and promotional gifts for every milestone.",
  "polar-camel":
    "Double-wall vacuum-insulated tumblers, bottles and mugs in dozens of powder-coated finishes.",
  drinkware:
    "Mugs, coasters, glassware and bar tools ready for crisp, permanent engraving.",
  "frames-and-decor":
    "Photo frames, slate signage and ornaments that turn moments into heirlooms.",
  "office-tech":
    "Journals, portfolios and desk accessories engraved for teams and gifting.",
};

const DEFAULT_ICON: IconKey = "gift";

/* ------------------------------------------------------------------ */
/* Deterministic derivation helpers                                    */
/* ------------------------------------------------------------------ */

function xmur3(str: string): () => number {
  let h = 1779033703 ^ str.length;
  for (let i = 0; i < str.length; i++) {
    h = Math.imul(h ^ str.charCodeAt(i), 3432918353);
    h = (h << 13) | (h >>> 19);
  }
  return () => {
    h = Math.imul(h ^ (h >>> 16), 2246822507);
    h = Math.imul(h ^ (h >>> 13), 3266489909);
    return (h ^= h >>> 16) >>> 0;
  };
}

function mulberry32(a: number): () => number {
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function rngFor(seed: string): () => number {
  return mulberry32(xmur3(seed)());
}

function intBetween(rng: () => number, min: number, max: number): number {
  return Math.floor(rng() * (max - min + 1)) + min;
}

const FONT_OPTIONS = [
  "Classic Serif",
  "Modern Sans",
  "Elegant Script",
  "Block Capitals",
];

function buildPersonalization(): PersonalizationOption[] {
  return [
    {
      id: "engraving",
      label: "Engraving text",
      type: "text",
      required: true,
      placeholder: "Name, date, or short message",
      helpText: "Up to 40 characters. Add line breaks or extra detail in notes.",
      maxLength: 40,
    },
    {
      id: "font",
      label: "Font style",
      type: "select",
      required: false,
      options: FONT_OPTIONS,
    },
  ];
}

function buildDescriptions(p: RawProduct): {
  description: string;
  longDescription: string;
} {
  const sizePart = p.size ? ` (${p.size})` : "";
  const description = `${p.name}${sizePart}, ready to personalize with laser engraving — add a name, date, monogram or logo for a crisp, permanent finish.`;
  const longDescription = `The ${p.name} is part of our ${p.subName} collection and is precision laser-engraved to order in the USA. Customize it with a name, date, monogram, or your company logo for a sharp, permanent mark that won't fade or peel — ideal for gifts, weddings, corporate orders and milestone awards. ${
    p.size ? `Size: ${p.size}. ` : ""
  }Personalization is included; volume and corporate pricing available on request.`;
  return { description, longDescription };
}

/* ------------------------------------------------------------------ */
/* Build the catalog once at module load                               */
/* ------------------------------------------------------------------ */

const jdsProducts: Product[] = data.products.map((p) => {
  const rng = rngFor(p.sku);
  const leadTimeDays = intBetween(rng, 5, 14);
  const badges: string[] = [];
  const roll = rng();
  if (roll < 0.14) badges.push("Bestseller");
  else if (roll < 0.26) badges.push("New");
  const { description, longDescription } = buildDescriptions(p);
  const image = p.image ?? p.imageFull ?? "";
  return {
    id: p.id,
    name: p.name,
    sku: p.sku,
    size: p.size,
    basePrice: p.price ?? 0,
    image,
    imageFull: p.imageFull ?? image,
    categoryId: p.categoryId,
    categorySlug: p.categorySlug,
    categoryName: p.categoryName,
    subcategorySlug: p.subSlug,
    subcategoryName: p.subName,
    description,
    longDescription,
    badges,
    leadTimeDays,
    personalization: buildPersonalization(),
  };
});

// FOMA's own inventory (foma-products.ts) is merged in alongside the reseller
// catalog without altering it.
const allProducts: Product[] = [...jdsProducts, ...fomaProducts];

const productById = new Map(allProducts.map((p) => [p.id, p]));

const productsByCategory = new Map<string, Product[]>();
const productsBySub = new Map<string, Product[]>();
for (const p of allProducts) {
  const cKey = p.categorySlug;
  const sKey = `${p.categorySlug}/${p.subcategorySlug}`;
  (productsByCategory.get(cKey) ?? productsByCategory.set(cKey, []).get(cKey)!).push(p);
  (productsBySub.get(sKey) ?? productsBySub.set(sKey, []).get(sKey)!).push(p);
}

const categories: Category[] = [...data.categories, FOMA_CATEGORY].map((c) => {
  const subcategories: Subcategory[] = c.subcategories.map((sc) => {
    const items = productsBySub.get(`${c.slug}/${sc.slug}`) ?? [];
    return {
      slug: sc.slug,
      name: sc.name,
      blurb: `Personalized ${sc.name.toLowerCase()}, laser-engraved to order.`,
      productCount: items.length,
    };
  });
  return {
    slug: c.slug,
    name: c.name,
    blurb: CATEGORY_BLURBS[c.slug] ?? `Personalized ${c.name.toLowerCase()}.`,
    icon: CATEGORY_ICONS[c.slug] ?? DEFAULT_ICON,
    subcategories,
    productCount: productsByCategory.get(c.slug)?.length ?? 0,
  };
});

const categoryBySlug = new Map(categories.map((c) => [c.slug, c]));

/* ------------------------------------------------------------------ */
/* Public API                                                          */
/* ------------------------------------------------------------------ */

export function getCategories(): Category[] {
  return categories;
}

export function getCategory(slug: string): Category | undefined {
  return categoryBySlug.get(slug);
}

export function getSubcategory(
  categorySlug: string,
  subSlug: string,
): { category: Category; subcategory: Subcategory } | undefined {
  const category = categoryBySlug.get(categorySlug);
  const subcategory = category?.subcategories.find((sc) => sc.slug === subSlug);
  if (!category || !subcategory) return undefined;
  return { category, subcategory };
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return productsByCategory.get(categorySlug) ?? [];
}

export function getProductsBySubcategory(
  categorySlug: string,
  subSlug: string,
): Product[] {
  return productsBySub.get(`${categorySlug}/${subSlug}`) ?? [];
}

export function getProduct(id: string): Product | undefined {
  return productById.get(id);
}

export function getAllProducts(): Product[] {
  return allProducts;
}

export function getProductCount(): number {
  return allProducts.length;
}

export function getFeaturedProducts(limit = 8): Product[] {
  const bestsellers = allProducts.filter((p) => p.badges.includes("Bestseller"));
  const pool = bestsellers.length >= limit ? bestsellers : allProducts;
  // Spread across categories for visual variety, then sort by rating.
  const byCat = new Map<string, Product[]>();
  for (const p of pool) {
    (byCat.get(p.categorySlug) ?? byCat.set(p.categorySlug, []).get(p.categorySlug)!).push(p);
  }
  // Deterministic per-SKU order so the featured rail is stable across renders
  // and varied across categories (round-robin below) without relying on ratings.
  const rank = (sku: string) => xmur3(sku)();
  for (const list of byCat.values()) list.sort((a, b) => rank(a.sku) - rank(b.sku));
  const out: Product[] = [];
  let added = true;
  while (out.length < limit && added) {
    added = false;
    for (const list of byCat.values()) {
      const next = list.shift();
      if (next) {
        out.push(next);
        added = true;
        if (out.length >= limit) break;
      }
    }
  }
  return out;
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  const sameSub = getProductsBySubcategory(
    product.categorySlug,
    product.subcategorySlug,
  ).filter((p) => p.id !== product.id);
  const sameCat = getProductsByCategory(product.categorySlug).filter(
    (p) =>
      p.id !== product.id && p.subcategorySlug !== product.subcategorySlug,
  );
  return [...sameSub, ...sameCat].slice(0, limit);
}

export function searchProducts(query: string, limit = 48): Product[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const terms = q.split(/\s+/);
  return allProducts
    .filter((p) => {
      const haystack =
        `${p.name} ${p.sku} ${p.categoryName} ${p.subcategoryName}`.toLowerCase();
      return terms.every((t) => haystack.includes(t));
    })
    .slice(0, limit);
}

/** Slim index for client-side live search suggestions. */
export function getSearchIndex(): SearchResult[] {
  return allProducts.map((p) => ({
    id: p.id,
    name: p.name,
    categoryName: p.categoryName,
    subcategoryName: p.subcategoryName,
    categorySlug: p.categorySlug,
    subcategorySlug: p.subcategorySlug,
    basePrice: p.basePrice,
    image: p.image,
  }));
}

export { formatPrice } from "@/lib/format";
