/**
 * FOMA FAMILY LLC's own (non-JDS) inventory.
 *
 * Unlike products.json (the reseller catalog auto-generated by .scrape/scrape.py),
 * these are FOMA's own products with real facts — name, price, description,
 * photography, colors and engraving options — captured from fomafamilyllc.com.
 * They are surfaced in a dedicated "Best Sellers" category. catalog.ts merges
 * these into the catalog alongside the reseller products without altering it.
 *
 * Images are served from FOMA's own domain (fomafamilyllc.com); the host is
 * whitelisted in next.config.ts and passes through the cloudinary() helper
 * untouched (it only rewrites res.cloudinary.com URLs).
 */

import type { Product } from "./types";

export const FOMA_CATEGORY = {
  id: "foma-best-seller",
  slug: "best-seller",
  name: "Best Sellers",
  subcategories: [
    { subId: "foma-tumblers", slug: "40oz-tumblers", name: "40oz Tumblers", count: 1 },
    { subId: "foma-lighters", slug: "lighters", name: "Lighters", count: 1 },
  ],
};

export const fomaProducts: Product[] = [
  {
    id: "foma-tumbler-40oz",
    name: "Custom Logo 40oz Tumbler with Handle & Straw",
    sku: "FOMA-TMB-40OZ",
    size: '40oz · 26.5 × 10 × 7.5 cm',
    basePrice: 10.39,
    image:
      "https://fomafamilyllc.com/image/cache/catalog/product_img/46174073/r/il/8113fc/5539447555/il-fullxfull.5539447555-657y-1200x1200.jpg.webp",
    imageFull:
      "https://fomafamilyllc.com/image/cache/catalog/product_img/46174073/r/il/8113fc/5539447555/il-fullxfull.5539447555-657y-1200x1200.jpg.webp",
    categoryId: "foma-best-seller",
    categorySlug: "best-seller",
    categoryName: "Best Sellers",
    subcategorySlug: "40oz-tumblers",
    subcategoryName: "40oz Tumblers",
    description:
      "Personalized 40oz stainless steel tumbler with handle & straw — double-wall vacuum insulated and laser-engraved to order in your choice of color.",
    longDescription:
      "Crafted from high-quality, durable stainless steel with a spacious 40oz capacity (26.5 × 10 × 7.5 cm). Double-wall vacuum insulation keeps drinks hot for up to 6 hours or cold for up to 12. Personalize it with a name, monogram, favorite quote, logo or design — laser-engraved for a crisp, permanent finish that won't fade or peel. Choose from seven powder-coated colors. An eco-friendly, reusable alternative to single-use bottles.",
    badges: ["Bestseller"],
    leadTimeDays: 5,
    personalization: [
      {
        id: "color",
        label: "Color",
        type: "select",
        required: true,
        options: [
          "Burgundy",
          "Bay Leaf",
          "Cream",
          "Fog",
          "Charcoal",
          "Black",
          "Rose Quartz",
        ],
      },
      {
        id: "engraving",
        label: "Engraving",
        type: "select",
        required: true,
        options: [
          "One Engraving (+$10.00)",
          "Two Engraving (+$15.00)",
          "Blank — no engraving",
        ],
        helpText: "Engraving upgrades are added to the base price as shown.",
      },
      {
        id: "engraving-text",
        label: "Engraving text",
        type: "text",
        required: false,
        placeholder: "Name, monogram, logo text, date, or short message",
        maxLength: 40,
        helpText: "Leave blank if you selected the no-engraving option.",
      },
    ],
  },
  {
    id: "foma-lighter-groomsmen",
    name: "Personalized Groomsmen Lighter",
    sku: "FOMA-LTR-GROOM",
    size: '2¼" × 1½"',
    basePrice: 7.99,
    image:
      "https://fomafamilyllc.com/image/cache/catalog/product_img/44697285/r/il/fbc780/5047408970/il-fullxfull.5047408970-afv7-1200x1200.jpg.webp",
    imageFull:
      "https://fomafamilyllc.com/image/cache/catalog/product_img/44697285/r/il/fbc780/5047408970/il-fullxfull.5047408970-afv7-1200x1200.jpg.webp",
    categoryId: "foma-best-seller",
    categorySlug: "best-seller",
    categoryName: "Best Sellers",
    subcategorySlug: "lighters",
    subcategoryName: "Lighters",
    description:
      "Personalized black-metal groomsmen lighter, laser-engraved to order — a classic gift for groomsmen, the groom, dad or husband.",
    longDescription:
      'A sleek black-metal lighter (2¼" × 1½") personalized with crisp laser engraving on the black metal surface that won\'t fade. Choose one- or two-side engraving, with an optional matching gift tin. A thoughtful groomsmen proposal or wedding-party keepsake. Made to order — production in 1–3 days.',
    badges: ["Bestseller"],
    leadTimeDays: 5,
    personalization: [
      {
        id: "engraving",
        label: "Engraving",
        type: "select",
        required: true,
        options: [
          "One Side (+$4.00)",
          "One Side + Tin (+$7.00)",
          "Two Side (+$5.00)",
          "Two Side + Tin (+$10.00)",
          "Blank / No Engraving",
        ],
      },
      {
        id: "engraving-text",
        label: "Engraving text",
        type: "text",
        required: false,
        placeholder: "Name, monogram, date, or short message",
        maxLength: 40,
      },
    ],
  },
];
