/**
 * FOMA FAMILY LLC's own (non-JDS) inventory.
 *
 * Unlike products.json (the reseller catalog auto-generated by .scrape/scrape.py),
 * these are FOMA's own products with real facts — name, price, description,
 * photography, colors and engraving options — captured from fomafamilyllc.com.
 * They are surfaced in a dedicated "Best Sellers" category. catalog.ts merges
 * these into the catalog alongside the reseller products without altering it.
 *
 * Images are served from FOMA's own domain (fomafamilyllc.com); the host is
 * whitelisted in next.config.ts and passes through the cloudinary() helper
 * untouched (it only rewrites res.cloudinary.com URLs).
 */

import type { Product } from "./types";

export const FOMA_CATEGORY = {
  id: "foma-best-seller",
  slug: "best-seller",
  name: "Best Sellers",
  subcategories: [
    { subId: "foma-tumblers", slug: "40oz-tumblers", name: "40oz Tumblers", count: 1 },
    { subId: "foma-lighters", slug: "lighters", name: "Lighters", count: 1 },
  ],
};

export const fomaProducts: Product[] = [
  {
    id: "foma-tumbler-40oz",
    name: "Custom Logo 40oz Tumbler with Handle & Straw",
    sku: "FOMA-TMB-40OZ",
    size: '40oz · 26.5 × 10 × 7.5 cm',
    basePrice: 10.39,
    image:
      "https://fomafamilyllc.com/image/cache/catalog/product_img/46174073/r/il/8113fc/5539447555/il-fullxfull.5539447555-657y-1200x1200.jpg.webp",
    imageFull:
      "https://fomafamilyllc.com/image/cache/catalog/product_img/46174073/r/il/8113fc/5539447555/il-fullxfull.5539447555-657y-1200x1200.jpg.webp",
    categoryId: "foma-best-seller",
    categorySlug: "best-seller",
    categoryName: "Best Sellers",
    subcategorySlug: "40oz-tumblers",
    subcategoryName: "40oz Tumblers",
    description:
      "Personalized 40oz stainless steel tumbler with handle & straw — double-wall vacuum insulated and laser-engraved to order in your choice of color.",
    longDescription:
      "Crafted from high-quality, durable stainless steel with a spacious 40oz capacity (26.5 × 10 × 7.5 cm). Double-wall vacuum insulation keeps drinks hot for up to 6 hours or cold for up to 12. Personalize it with a name, monogram, favorite quote, logo or design — laser-engraved for a crisp, permanent finish that won't fade or peel. Choose from seven powder-coated colors. An eco-friendly, reusable alternative to single-use bottles.",
    badges: ["Bestseller"],
    leadTimeDays: 5,
    personalization: [
      {
        id: "color",
        label: "Color",
        type: "select",
        required: true,
        options: [
          "Burgundy",
          "Bay Leaf",
          "Cream",
          "Fog",
          "Charcoal",
          "Black",
          "Rose Quartz",
        ],
      },
      {
        id: "engraving",
        label: "Engraving",
        type: "select",
        required: true,
        options: [
          "One Engraving (+$10.00)",
          "Two Engraving (+$15.00)",
          "Blank — no engraving",
        ],
        helpText: "Engraving upgrades are added to the base price as shown.",
      },
      {
        id: "engraving-text",
        label: "Engraving text",
        type: "text",
        required: false,
        placeholder: "Name, monogram, logo text, date, or short message",
        maxLength: 40,
        helpText: "Leave blank if you selected the no-engraving option.",
      },
    ],
  },
  {
    id: "foma-lighter-groomsmen",
    name: "Personalized Groomsmen Lighter",
    sku: "FOMA-LTR-GROOM",
    size: '2¼" × 1½"',
    basePrice: 7.99,
    image:
      "https://fomafamilyllc.com/image/cache/catalog/product_img/44697285/r/il/fbc780/5047408970/il-fullxfull.5047408970-afv7-1200x1200.jpg.webp",
    imageFull:
      "https://fomafamilyllc.com/image/cache/catalog/product_img/44697285/r/il/fbc780/5047408970/il-fullxfull.5047408970-afv7-1200x1200.jpg.webp",
    categoryId: "foma-best-seller",
    categorySlug: "best-seller",
    categoryName: "Best Sellers",
    subcategorySlug: "lighters",
    subcategoryName: "Lighters",
    description:
      "Personalized black-metal groomsmen lighter, laser-engraved to order — a classic gift for groomsmen, the groom, dad or husband.",
    longDescription:
      'A sleek black-metal lighter (2¼" × 1½") personalized with crisp laser engraving on the black metal surface that won\'t fade. Choose one- or two-side engraving, with an optional matching gift tin. A thoughtful groomsmen proposal or wedding-party keepsake. Made to order — production in 1–3 days.',
    badges: ["Bestseller"],
    leadTimeDays: 5,
    personalization: [
      {
        id: "engraving",
        label: "Engraving",
        type: "select",
        required: true,
        options: [
          "One Side (+$4.00)",
          "One Side + Tin (+$7.00)",
          "Two Side (+$5.00)",
          "Two Side + Tin (+$10.00)",
          "Blank / No Engraving",
        ],
      },
      {
        id: "engraving-text",
        label: "Engraving text",
        type: "text",
        required: false,
        placeholder: "Name, monogram, date, or short message",
        maxLength: 40,
      },
    ],
  },
  {
    id: "foma-tumbler-40oz-engraved",
    name: "Custom Engraved 40oz Stainless Steel Tumbler with Handle",
    sku: "FOMA-TMB-40OZ-ENG",
    size: '40oz · 26.5 × 10 × 7.5 cm',
    // TODO: placeholder wholesale reference price — confirm the real number
    // with the user before this goes to production. Hidden from buyers (B2B
    // pricing is gated behind "Add to quote"), but used internally.
    basePrice: 12.99,
    image: "/products/FOMA-TMB-40OZ-ENG/FOMA-TMB-40OZ-ENG.jpg",
    imageFull: "/products/FOMA-TMB-40OZ-ENG/FOMA-TMB-40OZ-ENG.jpg",
    categoryId: "foma-best-seller",
    categorySlug: "best-seller",
    categoryName: "Best Sellers",
    subcategorySlug: "40oz-tumblers",
    subcategoryName: "40oz Tumblers",
    description:
      "Personalized 40oz stainless steel tumbler with handle — double-wall vacuum insulated and laser-engraved to order with a name, monogram or floral design.",
    longDescription:
      "A 40oz double-wall vacuum-insulated stainless steel tumbler with a comfortable handle and spill-resistant lid. Laser-engraved to order with a name, monogram, floral motif or custom design for a crisp, permanent finish that won't fade or peel. Keeps drinks cold for up to 12 hours or hot for up to 6. Available in soft powder-coated colors — Rose Pink, Sage Green and Cream. A thoughtful personalized gift for birthdays, bridesmaids, weddings and the holidays. Made to order in the USA.",
    badges: ["New"],
    leadTimeDays: 5,
    personalization: [
      {
        id: "color",
        label: "Color",
        type: "select",
        required: true,
        options: ["Rose Pink", "Sage Green", "Cream"],
      },
      {
        id: "engraving-text",
        label: "Engraving text",
        type: "text",
        required: true,
        placeholder: "Name, monogram, or short message",
        maxLength: 40,
        helpText: "The name or text we'll laser-engrave on the tumbler.",
      },
    ],
  },
  {
    id: "foma-charcuterie-marble",
    name: "Marble Charcuterie Board – 11 Piece Set",
    sku: "FOMA-CHAR-MARB",
    size: "16.25 × 12 × 0.5 in · 11-piece set",
    // Wholesale reference price from the MakerFlo single-unit listing; hidden
    // from buyers (B2B pricing is gated behind "Add to quote"). Confirm the
    // real wholesale number with the user before relying on it internally.
    basePrice: 39.95,
    image: "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB.jpg",
    imageFull: "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB.jpg",
    images: [
      "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB.jpg",
      "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB_2.jpg",
      "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB_3.jpg",
      "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB_4.jpg",
      "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB_5.jpg",
      "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB_6.jpg",
      "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB_7.jpg",
      "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB_8.jpg",
    ],
    categoryId: "1",
    categorySlug: "gifts-and-promotions",
    categoryName: "Gifts & Promotions",
    subcategorySlug: "cutting-boards-cake-pans-kitchen",
    subcategoryName: "Cutting Boards, Cake Pans, Kitchen",
    weightLb: 7.94,
    dimensions: "16.25 × 12 × 0.5 in",
    description:
      "Marble and acacia wood charcuterie serving set — an 11-piece spread with three dipping spoons, three ceramic bowls and four cheese tools, laser-engraved to order.",
    longDescription:
      "A luxurious charcuterie serving set pairing heavy marble with premium acacia wood, prized for its one-of-a-kind grain. The 16.25 × 12 × 0.5 in board anchors a complete 11-piece set — three dipping spoons, three ceramic bowls and four charcuterie utensils — for a gift-ready spread. Each board ships individually packaged in a foam-protected white gift box. Acacia is a natural material: variations in grain, color and knots are unique to each piece, not defects. Personalize with laser engraving for a crisp, permanent finish that won't fade. Made to order.",
    badges: ["New"],
    leadTimeDays: 5,
    personalization: [
      {
        id: "personalization",
        label: "Personalization",
        type: "select",
        required: true,
        options: [
          "Laser Engraving (most popular)",
          "UV Printing",
          "UV DTF",
          "Blank — no personalization",
        ],
      },
      {
        id: "engraving-text",
        label: "Engraving text",
        type: "text",
        required: false,
        placeholder: "Name, monogram, logo text, or short message",
        maxLength: 40,
        helpText: "Leave blank if you selected the blank option.",
      },
    ],
  },
  {
    id: "foma-serving-board-marble",
    name: "Marble Serving Board Set – 5 Piece Set with Handle",
    sku: "FOMA-SERV-MARB",
    size: "15.5 × 9 × 0.5 in · 5-piece set",
    // Wholesale reference price from the MakerFlo single-unit listing; hidden
    // from buyers (B2B pricing is gated behind "Add to quote"). Confirm the
    // real wholesale number with the user before relying on it internally.
    basePrice: 19.95,
    image: "/products/FOMA-SERV-MARB/FOMA-SERV-MARB.jpg",
    imageFull: "/products/FOMA-SERV-MARB/FOMA-SERV-MARB.jpg",
    images: [
      "/products/FOMA-SERV-MARB/FOMA-SERV-MARB.jpg",
      "/products/FOMA-SERV-MARB/FOMA-SERV-MARB_2.jpg",
      "/products/FOMA-SERV-MARB/FOMA-SERV-MARB_3.jpg",
      "/products/FOMA-SERV-MARB/FOMA-SERV-MARB_4.jpg",
      "/products/FOMA-SERV-MARB/FOMA-SERV-MARB_5.jpg",
      "/products/FOMA-SERV-MARB/FOMA-SERV-MARB_6.jpg",
      "/products/FOMA-SERV-MARB/FOMA-SERV-MARB_7.jpg",
      "/products/FOMA-SERV-MARB/FOMA-SERV-MARB_8.jpg",
    ],
    categoryId: "1",
    categorySlug: "gifts-and-promotions",
    categoryName: "Gifts & Promotions",
    subcategorySlug: "cutting-boards-cake-pans-kitchen",
    subcategoryName: "Cutting Boards, Cake Pans, Kitchen",
    weightLb: 4.9,
    dimensions: "15.5 × 9 × 0.5 in",
    description:
      "Marble and acacia wood serving board with handle — a 5-piece set with four serving tools, laser-engraved to order.",
    longDescription:
      "A handled serving board crafted from premium acacia wood with elegant marble accents. The 15.5 × 9 × 0.5 in board comes as a complete 5-piece set with four serving tools and a convenient carry handle. Each board ships individually packaged in a foam-protected white gift box. Acacia is a natural material: variations in grain, color and knots are unique to each piece, not defects. Personalize with laser engraving, vinyl decals or epoxy for a crisp, lasting finish. Made to order.",
    badges: ["New"],
    leadTimeDays: 5,
    personalization: [
      {
        id: "personalization",
        label: "Personalization",
        type: "select",
        required: true,
        options: [
          "Laser Engraving (most popular)",
          "UV Printing",
          "UV DTF",
          "Blank — no personalization",
        ],
      },
      {
        id: "engraving-text",
        label: "Engraving text",
        type: "text",
        required: false,
        placeholder: "Name, monogram, logo text, or short message",
        maxLength: 40,
        helpText: "Leave blank if you selected the blank option.",
      },
    ],
  },
];
