/**
 * FOMA FAMILY LLC's own (non-JDS) inventory.
 *
 * Unlike products.json (the reseller catalog auto-generated by .scrape/scrape.py),
 * these are FOMA's own products with real facts — name, price, description,
 * photography, colors and engraving options — captured from fomafamilyllc.com.
 * They are surfaced in a dedicated "Best Sellers" category. catalog.ts merges
 * these into the catalog alongside the reseller products without altering it.
 *
 * Images are served from FOMA's own domain (fomafamilyllc.com); the host is
 * whitelisted in next.config.ts and passes through the cloudinary() helper
 * untouched (it only rewrites res.cloudinary.com URLs).
 */

import type { Product } from "./types";

export const FOMA_CATEGORY = {
  id: "foma-best-seller",
  slug: "best-seller",
  name: "Best Sellers",
  subcategories: [
    { subId: "foma-tumblers", slug: "40oz-tumblers", name: "40oz Tumblers", count: 1 },
    { subId: "foma-lighters", slug: "lighters", name: "Lighters", count: 1 },
  ],
};

export const fomaProducts: Product[] = [
  {
    id: "foma-tumbler-40oz",
    name: "Custom Logo 40oz Tumbler with Handle & Straw",
    sku: "FOMA-TMB-40OZ",
    size: '40oz · 26.5 × 10 × 7.5 cm',
    basePrice: 10.39,
    image:
      "https://fomafamilyllc.com/image/cache/catalog/product_img/46174073/r/il/8113fc/5539447555/il-fullxfull.5539447555-657y-1200x1200.jpg.webp",
    imageFull:
      "https://fomafamilyllc.com/image/cache/catalog/product_img/46174073/r/il/8113fc/5539447555/il-fullxfull.5539447555-657y-1200x1200.jpg.webp",
    categoryId: "foma-best-seller",
    categorySlug: "best-seller",
    categoryName: "Best Sellers",
    subcategorySlug: "40oz-tumblers",
    subcategoryName: "40oz Tumblers",
    description:
      "Personalized 40oz stainless steel tumbler with handle & straw — double-wall vacuum insulated and laser-engraved to order in your choice of color.",
    longDescription:
      "Crafted from high-quality, durable stainless steel with a spacious 40oz capacity (26.5 × 10 × 7.5 cm). Double-wall vacuum insulation keeps drinks hot for up to 6 hours or cold for up to 12. Personalize it with a name, monogram, favorite quote, logo or design — laser-engraved for a crisp, permanent finish that won't fade or peel. Choose from seven powder-coated colors. An eco-friendly, reusable alternative to single-use bottles.",
    badges: ["Bestseller"],
    leadTimeDays: 5,
    personalization: [
      {
        id: "color",
        label: "Color",
        type: "select",
        required: true,
        options: [
          "Burgundy",
          "Bay Leaf",
          "Cream",
          "Fog",
          "Charcoal",
          "Black",
          "Rose Quartz",
        ],
      },
      {
        id: "engraving",
        label: "Engraving",
        type: "select",
        required: true,
        options: [
          "One Engraving (+$10.00)",
          "Two Engraving (+$15.00)",
          "Blank — no engraving",
        ],
        helpText: "Engraving upgrades are added to the base price as shown.",
      },
      {
        id: "engraving-text",
        label: "Engraving text",
        type: "text",
        required: false,
        placeholder: "Name, monogram, logo text, date, or short message",
        maxLength: 40,
        helpText: "Leave blank if you selected the no-engraving option.",
      },
    ],
  },
  {
    id: "foma-lighter-groomsmen",
    name: "Personalized Groomsmen Lighter",
    sku: "FOMA-LTR-GROOM",
    size: '2¼" × 1½"',
    basePrice: 7.99,
    image:
      "https://fomafamilyllc.com/image/cache/catalog/product_img/44697285/r/il/fbc780/5047408970/il-fullxfull.5047408970-afv7-1200x1200.jpg.webp",
    imageFull:
      "https://fomafamilyllc.com/image/cache/catalog/product_img/44697285/r/il/fbc780/5047408970/il-fullxfull.5047408970-afv7-1200x1200.jpg.webp",
    categoryId: "foma-best-seller",
    categorySlug: "best-seller",
    categoryName: "Best Sellers",
    subcategorySlug: "lighters",
    subcategoryName: "Lighters",
    description:
      "Personalized black-metal groomsmen lighter, laser-engraved to order — a classic gift for groomsmen, the groom, dad or husband.",
    longDescription:
      'A sleek black-metal lighter (2¼" × 1½") personalized with crisp laser engraving on the black metal surface that won\'t fade. Choose one- or two-side engraving, with an optional matching gift tin. A thoughtful groomsmen proposal or wedding-party keepsake. Made to order — production in 1–3 days.',
    badges: ["Bestseller"],
    leadTimeDays: 5,
    personalization: [
      {
        id: "engraving",
        label: "Engraving",
        type: "select",
        required: true,
        options: [
          "One Side (+$4.00)",
          "One Side + Tin (+$7.00)",
          "Two Side (+$5.00)",
          "Two Side + Tin (+$10.00)",
          "Blank / No Engraving",
        ],
      },
      {
        id: "engraving-text",
        label: "Engraving text",
        type: "text",
        required: false,
        placeholder: "Name, monogram, date, or short message",
        maxLength: 40,
      },
    ],
  },
  {
    id: "foma-tumbler-40oz-engraved",
    name: "Personalized 40 oz Stainless Steel Tumbler with Handle & Straw – Custom Engraved Name & Birth Flower",
    sku: "FOMA-TMB-40OZ-ENG",
    size: '40oz · 12 × 6 in',
    // FOMA's own Amazon listing (ASIN B0DNY7LRFS) retails at $24.95. basePrice
    // here is a placeholder wholesale ref — hidden from buyers (B2B pricing is
    // gated behind "Add to quote"). Confirm the real wholesale number.
    basePrice: 12.99,
    image: "/products/FOMA-TMB-40OZ-ENG/FOMA-TMB-40OZ-ENG.jpg",
    imageFull: "/products/FOMA-TMB-40OZ-ENG/FOMA-TMB-40OZ-ENG.jpg",
    images: [
      "/products/FOMA-TMB-40OZ-ENG/FOMA-TMB-40OZ-ENG.jpg",
      "/products/FOMA-TMB-40OZ-ENG/FOMA-TMB-40OZ-ENG_2.jpg",
      "/products/FOMA-TMB-40OZ-ENG/FOMA-TMB-40OZ-ENG_3.jpg",
      "/products/FOMA-TMB-40OZ-ENG/FOMA-TMB-40OZ-ENG_4.jpg",
      "/products/FOMA-TMB-40OZ-ENG/FOMA-TMB-40OZ-ENG_5.jpg",
      "/products/FOMA-TMB-40OZ-ENG/FOMA-TMB-40OZ-ENG_6.jpg",
    ],
    categoryId: "foma-best-seller",
    categorySlug: "best-seller",
    categoryName: "Best Sellers",
    subcategorySlug: "40oz-tumblers",
    subcategoryName: "40oz Tumblers",
    description:
      "Personalized 40 oz stainless steel tumbler with handle and straw — double-wall vacuum insulated and laser-engraved to order with a custom name and birth flower. Ships next day.",
    longDescription:
      "FOMA FAMILY's 40 oz tumbler in 18/8 stainless steel with double-wall vacuum insulation and a thermal copper lining — keeps drinks cold for up to 12 hours or hot for up to 6. Comfortable ergonomic handle, BPA-free clear sliding lid and a reusable straw for work, gym or travel. Laser-engraved to order with a name, monogram or birth-flower design for a crisp, permanent finish that won't fade or peel. Choose from 13 powder-coated colors — Black, Charcoal, Cream, Lilac, Fog, Rose Quartz, Hot Pink, Forest, Azure, Eucalyptus, Bay Leaf, White and Light Pink. BPA-free and built for reuse. A thoughtful personalized gift for birthdays, bridesmaids, weddings and the holidays — ships next day.",
    badges: ["Bestseller"],
    leadTimeDays: 1,
    personalization: [
      {
        id: "color",
        label: "Color",
        type: "select",
        required: true,
        options: [
          "Black",
          "Charcoal",
          "Cream",
          "Lilac",
          "Fog",
          "Rose Quartz",
          "Hot Pink",
          "Forest",
          "Azure",
          "Eucalyptus",
          "Bay Leaf",
          "White",
          "Light Pink",
        ],
      },
      {
        id: "engraving-text",
        label: "Engraving text",
        type: "text",
        required: true,
        placeholder: "Name, monogram, or birth-flower message",
        maxLength: 40,
        helpText: "The name or text we'll laser-engrave on the tumbler.",
      },
    ],
  },
  {
    id: "foma-charcuterie-marble",
    name: "Marble Charcuterie Board – 11 Piece Set",
    sku: "FOMA-CHAR-MARB",
    size: "16.25 × 12 × 0.5 in · 11-piece set",
    // Wholesale reference price from the MakerFlo single-unit listing; hidden
    // from buyers (B2B pricing is gated behind "Add to quote"). Confirm the
    // real wholesale number with the user before relying on it internally.
    basePrice: 39.95,
    image: "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB.jpg",
    imageFull: "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB.jpg",
    images: [
      "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB.jpg",
      "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB_2.jpg",
      "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB_3.jpg",
      "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB_4.jpg",
      "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB_5.jpg",
      "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB_6.jpg",
      "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB_7.jpg",
      "/products/FOMA-CHAR-MARB/FOMA-CHAR-MARB_8.jpg",
    ],
    categoryId: "1",
    categorySlug: "gifts-and-promotions",
    categoryName: "Gifts & Promotions",
    subcategorySlug: "cutting-boards-cake-pans-kitchen",
    subcategoryName: "Cutting Boards, Cake Pans, Kitchen",
    weightLb: 7.94,
    dimensions: "16.25 × 12 × 0.5 in",
    description:
      "Marble and acacia wood charcuterie serving set — an 11-piece spread with three dipping spoons, three ceramic bowls and four cheese tools, laser-engraved to order.",
    longDescription:
      "A luxurious charcuterie serving set pairing heavy marble with premium acacia wood, prized for its one-of-a-kind grain. The 16.25 × 12 × 0.5 in board anchors a complete 11-piece set — three dipping spoons, three ceramic bowls and four charcuterie utensils — for a gift-ready spread. Each board ships individually packaged in a foam-protected white gift box. Acacia is a natural material: variations in grain, color and knots are unique to each piece, not defects. Personalize with laser engraving for a crisp, permanent finish that won't fade. Made to order.",
    badges: ["New"],
    leadTimeDays: 5,
    personalization: [
      {
        id: "personalization",
        label: "Personalization",
        type: "select",
        required: true,
        options: [
          "Laser Engraving (most popular)",
          "UV Printing",
          "UV DTF",
          "Blank — no personalization",
        ],
      },
      {
        id: "engraving-text",
        label: "Engraving text",
        type: "text",
        required: false,
        placeholder: "Name, monogram, logo text, or short message",
        maxLength: 40,
        helpText: "Leave blank if you selected the blank option.",
      },
    ],
  },
  {
    id: "foma-serving-board-marble",
    name: "Marble Serving Board Set – 5 Piece Set with Handle",
    sku: "FOMA-SERV-MARB",
    size: "15.5 × 9 × 0.5 in · 5-piece set",
    // Wholesale reference price from the MakerFlo single-unit listing; hidden
    // from buyers (B2B pricing is gated behind "Add to quote"). Confirm the
    // real wholesale number with the user before relying on it internally.
    basePrice: 19.95,
    image: "/products/FOMA-SERV-MARB/FOMA-SERV-MARB.jpg",
    imageFull: "/products/FOMA-SERV-MARB/FOMA-SERV-MARB.jpg",
    images: [
      "/products/FOMA-SERV-MARB/FOMA-SERV-MARB.jpg",
      "/products/FOMA-SERV-MARB/FOMA-SERV-MARB_2.jpg",
      "/products/FOMA-SERV-MARB/FOMA-SERV-MARB_3.jpg",
      "/products/FOMA-SERV-MARB/FOMA-SERV-MARB_4.jpg",
      "/products/FOMA-SERV-MARB/FOMA-SERV-MARB_5.jpg",
      "/products/FOMA-SERV-MARB/FOMA-SERV-MARB_6.jpg",
      "/products/FOMA-SERV-MARB/FOMA-SERV-MARB_7.jpg",
      "/products/FOMA-SERV-MARB/FOMA-SERV-MARB_8.jpg",
    ],
    categoryId: "1",
    categorySlug: "gifts-and-promotions",
    categoryName: "Gifts & Promotions",
    subcategorySlug: "cutting-boards-cake-pans-kitchen",
    subcategoryName: "Cutting Boards, Cake Pans, Kitchen",
    weightLb: 4.9,
    dimensions: "15.5 × 9 × 0.5 in",
    description:
      "Marble and acacia wood serving board with handle — a 5-piece set with four serving tools, laser-engraved to order.",
    longDescription:
      "A handled serving board crafted from premium acacia wood with elegant marble accents. The 15.5 × 9 × 0.5 in board comes as a complete 5-piece set with four serving tools and a convenient carry handle. Each board ships individually packaged in a foam-protected white gift box. Acacia is a natural material: variations in grain, color and knots are unique to each piece, not defects. Personalize with laser engraving, vinyl decals or epoxy for a crisp, lasting finish. Made to order.",
    badges: ["New"],
    leadTimeDays: 5,
    personalization: [
      {
        id: "personalization",
        label: "Personalization",
        type: "select",
        required: true,
        options: [
          "Laser Engraving (most popular)",
          "UV Printing",
          "UV DTF",
          "Blank — no personalization",
        ],
      },
      {
        id: "engraving-text",
        label: "Engraving text",
        type: "text",
        required: false,
        placeholder: "Name, monogram, logo text, or short message",
        maxLength: 40,
        helpText: "Leave blank if you selected the blank option.",
      },
    ],
  },
  {
    id: "foma-bbq-grill-set-11pc",
    name: "BBQ Grill Set with Case – 11 Piece Set",
    sku: "FOMA-BBQ-11PC",
    size: "18 × 6.25 × 3 in · 11-piece set",
    // Wholesale reference price from the MakerFlo single-unit listing; hidden
    // from buyers (B2B pricing is gated behind "Add to quote"). Confirm the
    // real wholesale number with the user before relying on it internally.
    basePrice: 39.95,
    image: "/products/FOMA-BBQ-11PC/FOMA-BBQ-11PC.jpg",
    imageFull: "/products/FOMA-BBQ-11PC/FOMA-BBQ-11PC.jpg",
    images: [
      "/products/FOMA-BBQ-11PC/FOMA-BBQ-11PC.jpg",
      "/products/FOMA-BBQ-11PC/FOMA-BBQ-11PC_2.jpg",
      "/products/FOMA-BBQ-11PC/FOMA-BBQ-11PC_3.jpg",
      "/products/FOMA-BBQ-11PC/FOMA-BBQ-11PC_4.jpg",
      "/products/FOMA-BBQ-11PC/FOMA-BBQ-11PC_5.jpg",
      "/products/FOMA-BBQ-11PC/FOMA-BBQ-11PC_6.jpg",
      "/products/FOMA-BBQ-11PC/FOMA-BBQ-11PC_7.jpg",
      "/products/FOMA-BBQ-11PC/FOMA-BBQ-11PC_8.jpg",
    ],
    categoryId: "1",
    categorySlug: "gifts-and-promotions",
    categoryName: "Gifts & Promotions",
    subcategorySlug: "bbq-sets-and-utensils",
    subcategoryName: "BBQ Sets and Utensils",
    weightLb: 6,
    dimensions: "18 × 6.25 × 3 in",
    description:
      "11-piece BBQ grill set with a wooden carrying case — spatula, tongs, brush, fork, knife, silicone hot glove and four skewers, laser-engraved to order.",
    longDescription:
      "A complete 11-piece BBQ grill set for the grill master — spatula, tongs, basting brush, fork, knife, silicone hot glove and four skewers, all housed in a wooden carrying case (18 × 6.25 × 3 in). Made from high-quality rubber wood; natural variations in grain, color and knots are unique to each piece, not defects. Personalize the case and tools with laser engraving for a crisp, permanent finish — a standout groomsman, Father's Day or housewarming gift. Made to order.",
    badges: ["New"],
    leadTimeDays: 5,
    personalization: [
      {
        id: "personalization",
        label: "Personalization",
        type: "select",
        required: true,
        options: [
          "Laser Engraving (most popular)",
          "UV Printing",
          "UV DTF",
          "Blank — no personalization",
        ],
      },
      {
        id: "engraving-text",
        label: "Engraving text",
        type: "text",
        required: false,
        placeholder: "Name, monogram, logo text, or short message",
        maxLength: 40,
        helpText: "Leave blank if you selected the blank option.",
      },
    ],
  },
  {
    id: "foma-dopp-kit-pu",
    name: "Vintage Brown PU Leather Travel Dopp Kit – Hanging Toiletry Bag",
    sku: "FOMA-DOPP-PU",
    size: "28 × 13 × 16 cm · 11 × 5.1 × 6.3 in",
    // Wholesale reference price from the Alibaba listing (10–999 pcs tier);
    // hidden from buyers (B2B pricing is gated behind "Add to quote"). Confirm
    // the real landed/wholesale number with the user before relying on it.
    basePrice: 5.88,
    image: "/products/FOMA-DOPP-PU/FOMA-DOPP-PU.jpg",
    imageFull: "/products/FOMA-DOPP-PU/FOMA-DOPP-PU.jpg",
    images: [
      "/products/FOMA-DOPP-PU/FOMA-DOPP-PU.jpg",
      "/products/FOMA-DOPP-PU/FOMA-DOPP-PU_2.jpg",
      "/products/FOMA-DOPP-PU/FOMA-DOPP-PU_3.jpg",
      "/products/FOMA-DOPP-PU/FOMA-DOPP-PU_4.jpg",
      "/products/FOMA-DOPP-PU/FOMA-DOPP-PU_5.jpg",
      "/products/FOMA-DOPP-PU/FOMA-DOPP-PU_6.jpg",
      "/products/FOMA-DOPP-PU/FOMA-DOPP-PU_7.jpg",
      "/products/FOMA-DOPP-PU/FOMA-DOPP-PU_8.jpg",
    ],
    categoryId: "1",
    categorySlug: "gifts-and-promotions",
    categoryName: "Gifts & Promotions",
    subcategorySlug: "travel-items",
    subcategoryName: "Travel Items",
    dimensions: "11 × 5.1 × 6.3 in",
    description:
      "Double-layer PU leather travel Dopp kit with a built-in hanging hook — a roomy, water-resistant toiletry organizer for men, personalized to order.",
    longDescription:
      "A premium vintage-look PU leather Dopp kit built for travel. The double-layer design opens flat for full access, with a built-in sturdy metal hook so it hangs hands-free from a towel bar or hook. Water-resistant lining protects your toiletries from spills, and the large 28 × 13 × 16 cm (11 × 5.1 × 6.3 in) capacity holds a full grooming kit. Zip closure with a carry handle. Available in reddish brown, yellowish-brown, coffee and black, and personalized with laser-engraved or embossed initials, name or logo. Made to order — a refined groomsmen, Father's Day or frequent-traveler gift.",
    badges: ["New"],
    leadTimeDays: 7,
    personalization: [
      {
        id: "color",
        label: "Color",
        type: "select",
        required: true,
        options: ["Reddish Brown", "Yellowish-Brown", "Coffee", "Black"],
      },
      {
        id: "personalization",
        label: "Personalization",
        type: "select",
        required: true,
        options: [
          "Laser Engraving (most popular)",
          "Emboss",
          "UV Printing",
          "Blank — no personalization",
        ],
      },
      {
        id: "engraving-text",
        label: "Engraving text",
        type: "text",
        required: false,
        placeholder: "Name, monogram, initials, or logo text",
        maxLength: 40,
        helpText: "Leave blank if you selected the blank option.",
      },
    ],
  },
  {
    id: "foma-ring-box-walnut",
    name: "Personalized Walnut Wood Ring Box – Hexagon 3-Slot Wedding Ring Holder",
    sku: "FOMA-RINGBOX-WAL",
    size: "77 × 67 × 38 mm · 3 × 2.6 × 1.5 in",
    // FOMA's own Amazon listing retails at $14.95. basePrice here is a hidden
    // reference (B2B pricing is gated behind "Add to quote").
    basePrice: 14.95,
    image: "/products/FOMA-RINGBOX-WAL/FOMA-RINGBOX-WAL.jpg",
    imageFull: "/products/FOMA-RINGBOX-WAL/FOMA-RINGBOX-WAL.jpg",
    images: [
      "/products/FOMA-RINGBOX-WAL/FOMA-RINGBOX-WAL.jpg",
      "/products/FOMA-RINGBOX-WAL/FOMA-RINGBOX-WAL_2.jpg",
      "/products/FOMA-RINGBOX-WAL/FOMA-RINGBOX-WAL_3.jpg",
      "/products/FOMA-RINGBOX-WAL/FOMA-RINGBOX-WAL_4.jpg",
      "/products/FOMA-RINGBOX-WAL/FOMA-RINGBOX-WAL_5.jpg",
      "/products/FOMA-RINGBOX-WAL/FOMA-RINGBOX-WAL_6.jpg",
      "/products/FOMA-RINGBOX-WAL/FOMA-RINGBOX-WAL_7.jpg",
      "/products/FOMA-RINGBOX-WAL/FOMA-RINGBOX-WAL_8.jpg",
    ],
    categoryId: "1",
    categorySlug: "gifts-and-promotions",
    categoryName: "Gifts & Promotions",
    subcategorySlug: "personal-items",
    subcategoryName: "Personal Items",
    weightLb: 0.11,
    dimensions: "3 × 2.6 × 1.5 in",
    description:
      "Personalized hexagon walnut wood ring box with a soft velvet 3-slot holder — a handmade keepsake for weddings, proposals and ring-bearer ceremonies, laser-engraved to order.",
    longDescription:
      "A handmade hexagon ring box turned from high-quality walnut wood, hand-polished to a smooth, warm finish and laser-engraved to order with names, initials or a date. The triple-slot black velvet interior cradles an engagement ring and two wedding bands, making it a refined ring-bearer or proposal keepsake box for the ceremony — and a lasting anniversary memento afterward. Compact at 77 × 67 × 38 mm (3 × 2.6 × 1.5 in). Each box is individually made, so the natural grain is unique to your piece. A heartfelt gift for engagements, weddings, anniversaries and couples.",
    badges: ["New"],
    leadTimeDays: 1,
    personalization: [
      {
        id: "wood",
        label: "Wood",
        type: "select",
        required: true,
        options: ["Walnut", "Koa"],
      },
      {
        id: "engraving-text",
        label: "Engraving text",
        type: "text",
        required: true,
        placeholder: "Names, initials, or date (e.g. R & V · 06.20.25)",
        maxLength: 40,
        helpText: "The names, initials or date we'll laser-engrave on the lid.",
      },
    ],
  },
  {
    id: "foma-cutting-board-bamboo",
    name: "Personalized Bamboo Engraved Cutting & Charcuterie Board – 16 × 11 × 1 in",
    sku: "FOMA-CUTBOARD-BMB",
    size: "16 × 11 × 1 in",
    // FOMA's own Amazon listing retails at $23.95. basePrice here is a hidden
    // reference (B2B pricing is gated behind "Add to quote").
    basePrice: 23.95,
    image: "/products/FOMA-CUTBOARD-BMB/FOMA-CUTBOARD-BMB.jpg",
    imageFull: "/products/FOMA-CUTBOARD-BMB/FOMA-CUTBOARD-BMB.jpg",
    images: [
      "/products/FOMA-CUTBOARD-BMB/FOMA-CUTBOARD-BMB.jpg",
      "/products/FOMA-CUTBOARD-BMB/FOMA-CUTBOARD-BMB_2.jpg",
      "/products/FOMA-CUTBOARD-BMB/FOMA-CUTBOARD-BMB_3.jpg",
      "/products/FOMA-CUTBOARD-BMB/FOMA-CUTBOARD-BMB_4.jpg",
      "/products/FOMA-CUTBOARD-BMB/FOMA-CUTBOARD-BMB_5.jpg",
      "/products/FOMA-CUTBOARD-BMB/FOMA-CUTBOARD-BMB_6.jpg",
      "/products/FOMA-CUTBOARD-BMB/FOMA-CUTBOARD-BMB_7.jpg",
      "/products/FOMA-CUTBOARD-BMB/FOMA-CUTBOARD-BMB_8.jpg",
    ],
    categoryId: "1",
    categorySlug: "gifts-and-promotions",
    categoryName: "Gifts & Promotions",
    subcategorySlug: "cutting-boards-cake-pans-kitchen",
    subcategoryName: "Cutting Boards, Cake Pans, Kitchen",
    dimensions: "16 × 11 × 1 in",
    description:
      "Personalized double-sided bamboo cutting & charcuterie board (16 × 11 × 1 in) with a juice groove and side handles — laser-engraved to order with a name, monogram or family design. Ships next day.",
    longDescription:
      "A large 16 × 11 × 1 in cutting and charcuterie board crafted from durable, elegant-grain bamboo. Double-sided so you can cut on one face and serve on the other, with a deep juice groove to catch runoff and carved side handles for an easy carry. Laser-engraved to order with a family name, monogram, initial-with-flower motif or custom design for a crisp, permanent finish — choose from designs for every initial letter. BPA-free, chemical-free and knife-friendly. Arrives in a gift box, making it a heartfelt wedding, anniversary, housewarming, birthday or Mother's/Father's Day gift. Ships next day.",
    badges: ["Bestseller"],
    leadTimeDays: 1,
    personalization: [
      {
        id: "design",
        label: "Engraving design",
        type: "select",
        required: true,
        options: [
          "Initial with flower",
          "Initial without flower",
          "Name / family name",
          "Custom design",
        ],
      },
      {
        id: "engraving-text",
        label: "Engraving text",
        type: "text",
        required: true,
        placeholder: "Family name, initial, or date (e.g. ALBERT · EST. 2025)",
        maxLength: 40,
        helpText: "The name, initial or text we'll laser-engrave on the board.",
      },
    ],
  },
];
